CREATE TABLE "Knives" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`knifeType`	TEXT,
	`knifeSkin`	TEXT,
	`knifeTexture`	TEXT NOT NULL,
	`knifeID`	INTEGER NOT NULL
);
INSERT INTO `Knives` VALUES(1,'Штык-нож','','Bayonet',1);
INSERT INTO `Knives` VALUES(2,'Штык-нож','Северный лес','Bayonet - Boreal Forest',1);
INSERT INTO `Knives` VALUES(3,'Штык-нож','Поверхностная закалка','Bayonet - Case Hardened',1);
INSERT INTO `Knives` VALUES(4,'Штык-нож','Кровавая паутина','Bayonet - Crimson Web',1);
INSERT INTO `Knives` VALUES(5,'Штык-нож','Градиен','Bayonet - Fade',1);
INSERT INTO `Knives` VALUES(6,'Штык-нож','Пиксельный камуфляж «Лес»','Bayonet - Forest DDPAT',1);
INSERT INTO `Knives` VALUES(7,'Штык-нож','Ночь','Bayonet - Night',1);
INSERT INTO `Knives` VALUES(8,'Штык-нож','Африканская сетка','Bayonet - Safari Mesh',1);
INSERT INTO `Knives` VALUES(9,'Штык-нож','Ожоги','Bayonet - Scorched',1);
INSERT INTO `Knives` VALUES(10,'Штык-нож','Убийство','Bayonet - Slaughter',1);
INSERT INTO `Knives` VALUES(11,'Штык-нож','Патина','Bayonet - Stained',1);
INSERT INTO `Knives` VALUES(12,'Штык-нож','Городская маскировка','Bayonet - Urban Masked',1);
INSERT INTO `Knives` VALUES(13,'Складной нож','','Flip Knife',2);
INSERT INTO `Knives` VALUES(14,'Складной нож','Северный лес','Flip Knife - Boreal Forest',2);
INSERT INTO `Knives` VALUES(15,'Складной нож','Поверхностная закалка','Flip Knife - Case Hardened',2);
INSERT INTO `Knives` VALUES(16,'Складной нож','Кровавая паутина','Flip Knife - Crimson Web',2);
INSERT INTO `Knives` VALUES(17,'Складной нож','Градиен','Flip Knife - Fade',2);
INSERT INTO `Knives` VALUES(18,'Складной нож','Пиксельный камуфляж «Лес»','Flip Knife - Forest DDPAT',2);
INSERT INTO `Knives` VALUES(19,'Складной нож','Ночь','Flip Knife - Night',2);
INSERT INTO `Knives` VALUES(20,'Складной нож','Африканская сетка','Flip Knife - Safari Mesh',2);
INSERT INTO `Knives` VALUES(21,'Складной нож','Ожоги','Flip Knife - Scorched',2);
INSERT INTO `Knives` VALUES(22,'Складной нож','Убийство','Flip Knife - Slaughter',2);
INSERT INTO `Knives` VALUES(23,'Складной нож','Патина','Flip Knife - Stained',2);
INSERT INTO `Knives` VALUES(24,'Складной нож','Городская маскировка','Flip Knife - Urban Masked',2);
INSERT INTO `Knives` VALUES(25,'Нож с лезвием-крюком','','Gut Knife',3);
INSERT INTO `Knives` VALUES(26,'Нож с лезвием-крюком','Вороненая сталь','Gut Knife - Blue Steel',3);
INSERT INTO `Knives` VALUES(27,'Нож с лезвием-крюком','Северный лес','Gut Knife - Boreal Forest',3);
INSERT INTO `Knives` VALUES(28,'Нож с лезвием-крюком','Поверхностная закалка','Gut Knife - Case Hardened',3);
INSERT INTO `Knives` VALUES(29,'Нож с лезвием-крюком','Кровавая паутина','Gut Knife - Crimson Web',3);
INSERT INTO `Knives` VALUES(30,'Нож с лезвием-крюком','Градиен','Gut Knife - Fade',3);
INSERT INTO `Knives` VALUES(31,'Нож с лезвием-крюком','Пиксельный камуфляж «Лес»','Gut Knife - Forest DDPAT',3);
INSERT INTO `Knives` VALUES(32,'Нож с лезвием-крюком','Ночь','Gut Knife - Night',3);
INSERT INTO `Knives` VALUES(33,'Нож с лезвием-крюком','Африканская сетка','Gut Knife - Safari Mesh',3);
INSERT INTO `Knives` VALUES(34,'Нож с лезвием-крюком','Ожоги','Gut Knife - Scorched',3);
INSERT INTO `Knives` VALUES(35,'Нож с лезвием-крюком','Убийство','Gut Knife - Slaughter',3);
INSERT INTO `Knives` VALUES(36,'Нож с лезвием-крюком','Патина','Gut Knife - Stained',3);
INSERT INTO `Knives` VALUES(37,'Нож с лезвием-крюком','Городская маскировка','Gut Knife - Urban Masked',3);
INSERT INTO `Knives` VALUES(38,'Охотничий нож','','Huntsman Knife',4);
INSERT INTO `Knives` VALUES(39,'Охотничий нож','Вороненая сталь','Huntsman Knife - Blue Steel',4);
INSERT INTO `Knives` VALUES(40,'Охотничий нож','Северный лес','Huntsman Knife - Boreal Forest',4);
INSERT INTO `Knives` VALUES(41,'Охотничий нож','Поверхностная закалка','Huntsman Knife - Case Hardened',4);
INSERT INTO `Knives` VALUES(42,'Охотничий нож','Кровавая паутина','Huntsman Knife - Crimson Web',4);
INSERT INTO `Knives` VALUES(43,'Охотничий нож','Градиен','Huntsman Knife - Fade',4);
INSERT INTO `Knives` VALUES(44,'Охотничий нож','Пиксельный камуфляж «Лес»','Huntsman Knife - Forest DDPAT',4);
INSERT INTO `Knives` VALUES(45,'Охотничий нож','Ночь','Huntsman Knife - Night',4);
INSERT INTO `Knives` VALUES(46,'Охотничий нож','Африканская сетка','Huntsman Knife - Safari Mesh',4);
INSERT INTO `Knives` VALUES(47,'Охотничий нож','Ожоги','Huntsman Knife - Scorched',4);
INSERT INTO `Knives` VALUES(48,'Охотничий нож','Убийство','Huntsman Knife - Slaughter',4);
INSERT INTO `Knives` VALUES(49,'Охотничий нож','Патина','Huntsman Knife - Stained',4);
INSERT INTO `Knives` VALUES(50,'Охотничий нож','Городская маскировка','Huntsman Knife - Urban Masked',4);
INSERT INTO `Knives` VALUES(51,'Керамбит','','Karambit',5);
INSERT INTO `Knives` VALUES(52,'Керамбит','Вороненая сталь','Karambit - Blue Steel',5);
INSERT INTO `Knives` VALUES(53,'Керамбит','Северный лес','Karambit - Boreal Forest',5);
INSERT INTO `Knives` VALUES(54,'Керамбит','Поверхностная закалка','Karambit - Case Hardened',5);
INSERT INTO `Knives` VALUES(55,'Керамбит','Градиен','Karambit - Fade',5);
INSERT INTO `Knives` VALUES(56,'Керамбит','Ночь','Karambit - Night',5);
INSERT INTO `Knives` VALUES(57,'Керамбит','Ожоги','Karambit - Scorched',5);
INSERT INTO `Knives` VALUES(58,'Керамбит','Убийство','Karambit - Slaughter',5);
INSERT INTO `Knives` VALUES(59,'Керамбит','Патина','Karambit - Stained',5);
INSERT INTO `Knives` VALUES(60,'Керамбит','Городская маскировка','Karambit - Urban Masked',5);
INSERT INTO `Knives` VALUES(61,'Штык-нож M9','','M9 Bayonet',6);
INSERT INTO `Knives` VALUES(62,'Штык-нож M9','Вороненая сталь','M9 Bayonet - Blue Steel',6);
INSERT INTO `Knives` VALUES(63,'Штык-нож M9','Северный лес','M9 Bayonet - Boreal Forest',6);
INSERT INTO `Knives` VALUES(64,'Штык-нож M9','Поверхностная закалка','M9 Bayonet - Case Hardened',6);
INSERT INTO `Knives` VALUES(65,'Штык-нож M9','Кровавая паутина','M9 Bayonet - Crimson Web',6);
INSERT INTO `Knives` VALUES(66,'Штык-нож M9','Градиен','M9 Bayonet - Fade',6);
INSERT INTO `Knives` VALUES(67,'Штык-нож M9','Пиксельный камуфляж «Лес»','M9 Bayonet - Forest DDPAT',6);
INSERT INTO `Knives` VALUES(68,'Штык-нож M9','Ночь','M9 Bayonet - Night',6);
INSERT INTO `Knives` VALUES(69,'Штык-нож M9','Африканская сетка','M9 Bayonet - Safari Mesh',6);
INSERT INTO `Knives` VALUES(70,'Штык-нож M9','Ожоги','M9 Bayonet - Scorched',6);
INSERT INTO `Knives` VALUES(71,'Штык-нож M9','Убийство','M9 Bayonet - Slaughter',6);
INSERT INTO `Knives` VALUES(72,'Штык-нож M9','Патина','M9 Bayonet - Stained',6);
INSERT INTO `Knives` VALUES(73,'Штык-нож M9','Городская маскировка','M9 Bayonet - Urban Masked',6);
INSERT INTO `Knives` VALUES(74,'Нож-бабочка','','Butterfly Knife',7);
INSERT INTO `Knives` VALUES(75,'Нож-бабочка','Вороненая сталь','Butterfly Knife - Blue Steel',7);
INSERT INTO `Knives` VALUES(76,'Нож-бабочка','Северный лес','Butterfly Knife - Boreal Forest',7);
INSERT INTO `Knives` VALUES(77,'Нож-бабочка','Поверхностная закалка','Butterfly Knife - Case Hardened',7);
INSERT INTO `Knives` VALUES(78,'Нож-бабочка','Кровавая паутина','Butterfly Knife - Crimson Web',7);
INSERT INTO `Knives` VALUES(79,'Нож-бабочка','Градиен','Butterfly Knife - Fade',7);
INSERT INTO `Knives` VALUES(80,'Нож-бабочка','Пиксельный камуфляж «Лес»','Butterfly Knife - Forest DDPAT',7);
INSERT INTO `Knives` VALUES(81,'Нож-бабочка','Ночь','Butterfly Knife - Night',7);
INSERT INTO `Knives` VALUES(82,'Нож-бабочка','Африканская сетка','Butterfly Knife - Safari Mesh',7);
INSERT INTO `Knives` VALUES(83,'Нож-бабочка','Ожоги','Butterfly Knife - Scorched',7);
INSERT INTO `Knives` VALUES(84,'Нож-бабочка','Убийство','Butterfly Knife - Slaughter',7);
INSERT INTO `Knives` VALUES(85,'Нож-бабочка','Патина','Butterfly Knife - Stained',7);
INSERT INTO `Knives` VALUES(86,'Нож-бабочка','Городская маскировка','Butterfly Knife - Urban Masked',7);
INSERT INTO `Knives` VALUES(87,'Штык-нож','Дамасская сталь','Bayonet - Damascus Steel',8);
INSERT INTO `Knives` VALUES(88,'Штык-нож','Doppler','Bayonet - Doppler',8);
INSERT INTO `Knives` VALUES(89,'Штык-нож','Marble Fade','Bayonet - Marble Fade',8);
INSERT INTO `Knives` VALUES(90,'Штык-нож','Пыльник','Bayonet - Rust Coat',8);
INSERT INTO `Knives` VALUES(91,'Штык-нож','Tiger Tooth','Bayonet - Tiger Tooth',8);
INSERT INTO `Knives` VALUES(92,'Складной нож','Дамасская сталь','Flip Knife - Damascus Steel',8);
INSERT INTO `Knives` VALUES(93,'Складной нож','Doppler','Flip Knife - Doppler',8);
INSERT INTO `Knives` VALUES(94,'Складной нож','Marble Fade','Flip Knife - Marble Fade',8);
INSERT INTO `Knives` VALUES(95,'Складной нож','Пыльник','Flip Knife - Rust Coat',8);
INSERT INTO `Knives` VALUES(96,'Складной нож','Tiger Tooth','Flip Knife - Tiger Tooth',8);
INSERT INTO `Knives` VALUES(97,'Нож с лезвием-крюком','Дамасская сталь','Gut Knife - Damascus Steel',8);
INSERT INTO `Knives` VALUES(98,'Нож с лезвием-крюком','Doppler','Gut Knife - Doppler',8);
INSERT INTO `Knives` VALUES(99,'Нож с лезвием-крюком','Marble Fade','Gut Knife - Marble Fade',8);
INSERT INTO `Knives` VALUES(100,'Нож с лезвием-крюком','Пыльник','Gut Knife - Rust Coat',8);
INSERT INTO `Knives` VALUES(101,'Нож с лезвием-крюком','Tiger Tooth','Gut Knife - Tiger Tooth',8);
INSERT INTO `Knives` VALUES(102,'Керамбит','Дамасская сталь','Karambit - Damascus Steel',8);
INSERT INTO `Knives` VALUES(103,'Керамбит','Doppler','Karambit - Doppler',8);
INSERT INTO `Knives` VALUES(104,'Керамбит','Marble Fade','Karambit - Marble Fade',8);
INSERT INTO `Knives` VALUES(105,'Керамбит','Пыльник','Karambit - Rust Coat',8);
INSERT INTO `Knives` VALUES(106,'Керамбит','Tiger Tooth','Karambit - Tiger Tooth',8);
INSERT INTO `Knives` VALUES(107,'Штык-нож M9','Дамасская сталь','M9 Bayonet - Damascus Steel',8);
INSERT INTO `Knives` VALUES(108,'Штык-нож M9','Doppler','M9 Bayonet - Doppler',8);
INSERT INTO `Knives` VALUES(109,'Штык-нож M9','Marble Fade','M9 Bayonet - Marble Fade',8);
INSERT INTO `Knives` VALUES(110,'Штык-нож M9','Пыльник','M9 Bayonet - Rust Coat',8);
INSERT INTO `Knives` VALUES(111,'Штык-нож M9','Tiger Tooth','M9 Bayonet - Tiger Tooth',8);
CREATE TABLE "Guns" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`gunType`	TEXT,
	`gunSkin`	TEXT,
	`gunTexture`	TEXT NOT NULL,
	`rarity`	INTEGER NOT NULL,
	`caseID`	INTEGER NOT NULL
);
INSERT INTO `Guns` VALUES(1,'MP7','Черепа','MP7 - Skulls',1,1);
INSERT INTO `Guns` VALUES(2,'SG 553','Ультрафиолет','SG 553 - Ultraviolet',1,1);
INSERT INTO `Guns` VALUES(3,'AUG','Крылья','AUG - Wings',1,1);
INSERT INTO `Guns` VALUES(4,'M4A1-S','Темная вода','M4A1-S - Dark Water',2,1);
INSERT INTO `Guns` VALUES(5,'USP-S','Темная вода','USP-S - Dark Water',2,1);
INSERT INTO `Guns` VALUES(6,'Glock-18','Татуировка дракона','Glock-18 - Dragon Tattoo',2,1);
INSERT INTO `Guns` VALUES(7,'Desert Eagle','Гипнотический','Desert Eagle - Hypnotic',3,1);
INSERT INTO `Guns` VALUES(8,'AK-47','Поверхностная закалка','AK-47 - Case Hardened',3,1);
INSERT INTO `Guns` VALUES(9,'AWP','Удар молнии','AWP - Lightning Strike',4,1);
INSERT INTO `Guns` VALUES(10,'редкий особый пункт','','Rare Special Item',5,1);
INSERT INTO `Guns` VALUES(11,'Tec-9','Синий титан','Tec-9 - Blue Titanium',1,2);
INSERT INTO `Guns` VALUES(12,'M4A1-S','Кровавый тигр','M4A1-S - Blood Tiger',1,2);
INSERT INTO `Guns` VALUES(13,'FAMAS','Гексан','FAMAS - Hexane',1,2);
INSERT INTO `Guns` VALUES(14,'P250','Улей','P250 - Hive',1,2);
INSERT INTO `Guns` VALUES(15,'SCAR-20','Кровавая паутина','SCAR-20 - Crimson Web',1,2);
INSERT INTO `Guns` VALUES(16,'Five-SeveN','Поверхностная закалка','Five-SeveN - Case Hardened',2,2);
INSERT INTO `Guns` VALUES(17,'MP9','Гипнотический','MP9 - Hypnotic',2,2);
INSERT INTO `Guns` VALUES(18,'Nova','Графит','Nova - Graphite',2,2);
INSERT INTO `Guns` VALUES(19,'Dual Berettas','Гемоглобин','Dual Berettas - Hemoglobin',2,2);
INSERT INTO `Guns` VALUES(20,'P90','Хладнокровный','P90 - Cold Blooded',3,2);
INSERT INTO `Guns` VALUES(21,'USP-S','Сыворотка','USP-S - Serum',3,2);
INSERT INTO `Guns` VALUES(22,'SSG 08','Кровь в воде','SSG 08 - Blood in the Water',4,2);
INSERT INTO `Guns` VALUES(23,'редкий особый пункт','','Rare Special Item',5,2);
INSERT INTO `Guns` VALUES(24,'CZ75-Auto','Кровавая паутина','CZ75-Auto - Crimson Web',1,3);
INSERT INTO `Guns` VALUES(25,'P2000','Красные фрагменты','P2000 - Red FragCam',1,3);
INSERT INTO `Guns` VALUES(26,'Dual Berettas','Пантера','Dual Berettas - Panther',1,3);
INSERT INTO `Guns` VALUES(27,'USP-S','Нержавейка','USP-S - Stainless',1,3);
INSERT INTO `Guns` VALUES(28,'Glock-18','Синяя трещина','Glock-18 - Blue Fissure',1,3);
INSERT INTO `Guns` VALUES(29,'CZ75-Auto','Листовая сталь','CZ75-Auto - Tread Plate',2,3);
INSERT INTO `Guns` VALUES(30,'Tec-9','Частица титана','Tec-9 - Titanium Bit',2,3);
INSERT INTO `Guns` VALUES(31,'Desert Eagle','Наследие','Desert Eagle - Heirloom',2,3);
INSERT INTO `Guns` VALUES(32,'Five-SeveN','Медная галактика','Five-SeveN - Copper Galaxy',2,3);
INSERT INTO `Guns` VALUES(33,'CZ75-Auto','Новая фуксия','CZ75-Auto - The Fuschia Is Now',3,3);
INSERT INTO `Guns` VALUES(34,'P250','Цвета прибоя','P250 - Undertow',3,3);
INSERT INTO `Guns` VALUES(35,'CZ75-Auto','Виктория','CZ75-Auto - Victoria',4,3);
INSERT INTO `Guns` VALUES(38,'Nova','Буря','Nova - Tempest',1,4);
INSERT INTO `Guns` VALUES(39,'Dual Berettas','Черная лимба','Dual Berettas - Black Limba',1,4);
INSERT INTO `Guns` VALUES(40,'UMP-45','Груда костей','UMP-45 - Bone Pile',1,4);
INSERT INTO `Guns` VALUES(41,'SG 553','Брызги волны','SG 553 - Wave Spray',1,4);
INSERT INTO `Guns` VALUES(42,'Galil AR','Осколки','Galil AR - Shattered',1,4);
INSERT INTO `Guns` VALUES(43,'G3SG1','Витраж','G3SG1 - Demeter',1,4);
INSERT INTO `Guns` VALUES(44,'M4A1-S','Чистая вода','M4A1-S - Bright Water',2,4);
INSERT INTO `Guns` VALUES(45,'M4A4','Зірка','M4A4 - Zirka',2,4);
INSERT INTO `Guns` VALUES(46,'MAC-10','Гравировка','MAC-10 - Graven',2,4);
INSERT INTO `Guns` VALUES(47,'USP-S','Камуфляж','USP-S - Overgrowth',2,4);
INSERT INTO `Guns` VALUES(48,'P90','Изумрудный дракон','P90 - Emerald Dragon',3,4);
INSERT INTO `Guns` VALUES(49,'P2000','Океанская пена
','P2000 - Ocean Foam',3,4);
INSERT INTO `Guns` VALUES(50,'AWP','Графит','AWP - Graphite',3,4);
INSERT INTO `Guns` VALUES(51,'Desert Eagle','Золотой карп','Desert Eagle - Golden Koi',4,4);
INSERT INTO `Guns` VALUES(52,'AK-47','Огненный змей','AK-47 - Fire Serpent',4,4);
INSERT INTO `Guns` VALUES(53,'ПП-19 Бизон','Синие полутона','PP-Bizon - Cobalt Halftone',1,5);
INSERT INTO `Guns` VALUES(54,'M249','Магма','M249 - Magma',1,5);
INSERT INTO `Guns` VALUES(55,'Five-SeveN','Ками','Five-SeveN - Kami',1,5);
INSERT INTO `Guns` VALUES(56,'Galil AR','Песчаная буря','Galil AR - Sandstorm',1,5);
INSERT INTO `Guns` VALUES(57,'Nova','Восходящий череп','Nova - Rising Skull',2,5);
INSERT INTO `Guns` VALUES(58,'MP9','Железная роза','MP9 - Rose Iron',2,5);
INSERT INTO `Guns` VALUES(59,'Dual Berettas','Причал','Dual Berettas - Marina',2,5);
INSERT INTO `Guns` VALUES(60,'FAMAS','Пульс','FAMAS - Pulse',2,5);
INSERT INTO `Guns` VALUES(61,'AWP','Красная линия','AWP - Redline',3,5);
INSERT INTO `Guns` VALUES(62,'P250','Роспись','P250 - Mehndi',3,5);
INSERT INTO `Guns` VALUES(63,'M4A1-S','Страж','M4A1-S - Guardian',3,5);
INSERT INTO `Guns` VALUES(64,'Sawed-Off','Кракен','Sawed-Off - The Kraken',4,5);
INSERT INTO `Guns` VALUES(65,'M4A4','Азимов','M4A4 - Asiimov',4,5);
INSERT INTO `Guns` VALUES(66,'редкий особый пункт','','Rare Special Item',5,5);
INSERT INTO `Guns` VALUES(67,'UMP-45','Капрал','UMP-45 - Corporal',1,6);
INSERT INTO `Guns` VALUES(68,'Negev','Почва','Negev - Terrain',1,6);
INSERT INTO `Guns` VALUES(69,'Tec-9','Песчаная буря','Tec-9 - Sandstorm',1,6);
INSERT INTO `Guns` VALUES(70,'MAG-7','Райский страж','MAG-7 - Heaven Guard',1,6);
INSERT INTO `Guns` VALUES(71,'MAC-10','Жар','MAC-10 - Heat',2,6);
INSERT INTO `Guns` VALUES(72,'SG 553','Пульс','SG 553 - Pulse',2,6);
INSERT INTO `Guns` VALUES(73,'FAMAS','Сержант','FAMAS - Sergeant',2,6);
INSERT INTO `Guns` VALUES(74,'USP-S','Страж','USP-S - Guardian',2,6);
INSERT INTO `Guns` VALUES(75,'AK-47','Красная линия','AK-47 - Redline',3,6);
INSERT INTO `Guns` VALUES(76,'P90','Треугольник','P90 - Trigon',3,6);
INSERT INTO `Guns` VALUES(77,'Nova','Антиквариат','Nova - Antique',3,6);
INSERT INTO `Guns` VALUES(78,'AWP','Азимов','AWP - Asiimov',4,6);
INSERT INTO `Guns` VALUES(79,'AUG','Хамелеон','AUG - Chameleon',4,6);
INSERT INTO `Guns` VALUES(80,'редкий особый пункт','','Rare Special Item',5,6);
INSERT INTO `Guns` VALUES(81,'Tec-9','Айзек','Tec-9 - Isaac',1,7);
INSERT INTO `Guns` VALUES(82,'SSG 08','Когти','SSG 08 - Slashed',1,7);
INSERT INTO `Guns` VALUES(83,'Dual Berettas','Возмездие','Dual Berettas - Retribution',1,7);
INSERT INTO `Guns` VALUES(84,'Galil AR','Ками','Galil AR - Kami',1,7);
INSERT INTO `Guns` VALUES(85,'P90','Война в пустыне','P90 - Desert Warfare',1,7);
INSERT INTO `Guns` VALUES(86,'CZ75-Auto','Отравленный дротик','CZ75-Auto - Poison Dart',1,7);
INSERT INTO `Guns` VALUES(87,'AUG','Закрученный','AUG - Torque',2,7);
INSERT INTO `Guns` VALUES(88,'ПП-19 Бизон','Антиквариат','PP-Bizon - Antique',2,7);
INSERT INTO `Guns` VALUES(89,'MAC-10','Проклятие','MAC-10 - Curse',2,7);
INSERT INTO `Guns` VALUES(90,'XM1014','Райский страж','XM1014 - Heaven Guard',2,7);
INSERT INTO `Guns` VALUES(91,'M4A1-S','Атомный сплав','M4A1-S - Atomic Alloy',3,7);
INSERT INTO `Guns` VALUES(92,'SCAR-20','Сайрекс','SCAR-20 - Cyrex',3,7);
INSERT INTO `Guns` VALUES(93,'USP-S','Орион','USP-S - Orion',3,7);
INSERT INTO `Guns` VALUES(94,'AK-47','Вулкан','AK-47 - Vulcan',4,7);
INSERT INTO `Guns` VALUES(95,'M4A4','Вой','M4A4 - Howl',4,7);
INSERT INTO `Guns` VALUES(96,'Охотничий нож','','Huntsman Knife',5,7);
INSERT INTO `Guns` VALUES(97,'Tec-9','Айзек','Tec-9 - Isaac',1,8);
INSERT INTO `Guns` VALUES(98,'SSG 08','Когти','SSG 08 - Slashed',1,8);
INSERT INTO `Guns` VALUES(99,'Galil AR','Ками','Galil AR - Kami',1,8);
INSERT INTO `Guns` VALUES(100,'CZ75-Auto','Спираль','CZ75-Auto - Twist',1,8);
INSERT INTO `Guns` VALUES(101,'P90','Модуль','P90 - Module',1,8);
INSERT INTO `Guns` VALUES(102,'P2000','ПульсПульс','P2000 - Pulse',1,8);
INSERT INTO `Guns` VALUES(103,'AUG','Закрученный','AUG - Torque',2,8);
INSERT INTO `Guns` VALUES(104,'ПП-19 Бизон','Антиквариат','PP-Bizon - Antique',2,8);
INSERT INTO `Guns` VALUES(105,'MAC-10','Обгорание','MAC-10 - Tatter',2,8);
INSERT INTO `Guns` VALUES(106,'XM1014','Райский страж','XM1014 - Heaven Guard',2,8);
INSERT INTO `Guns` VALUES(107,'M4A1-S','Атомный сплав','M4A1-S - Atomic Alloy',3,8);
INSERT INTO `Guns` VALUES(108,'SCAR-20','Сайрекс','SCAR-20 - Cyrex',3,8);
INSERT INTO `Guns` VALUES(109,'USP-S','Кайман','USP-S - Caiman',3,8);
INSERT INTO `Guns` VALUES(110,'AK-47','Вулкан','AK-47 - Vulcan',4,8);
INSERT INTO `Guns` VALUES(111,'M4A4','Пустынная атака','M4A4 - Desert-Strike',4,8);
INSERT INTO `Guns` VALUES(112,'Охотничий нож','','Huntsman Knife',5,8);
INSERT INTO `Guns` VALUES(113,'MP7','Городская опасность','MP7 - Urban Hazard',1,9);
INSERT INTO `Guns` VALUES(114,'Negev','Пустынная атака','Negev - Desert-Strike',1,9);
INSERT INTO `Guns` VALUES(115,'P2000','Слоновая кость','P2000 - Ivory',1,9);
INSERT INTO `Guns` VALUES(116,'SSG 08','Пучина','SSG 08 - Abyss',1,9);
INSERT INTO `Guns` VALUES(117,'UMP-45','Лабиринт','UMP-45 - Labyrinth',1,9);
INSERT INTO `Guns` VALUES(118,'ПП-19 Бизон','Осирис','PP-Bizon - Osiris',2,9);
INSERT INTO `Guns` VALUES(119,'CZ75-Auto','Тигр','CZ75-Auto - Tigris',2,9);
INSERT INTO `Guns` VALUES(120,'Nova','Карп кои','Nova - Koi',2,9);
INSERT INTO `Guns` VALUES(121,'P250','Сверхновая','P250 - Supernova',2,9);
INSERT INTO `Guns` VALUES(122,'Desert Eagle','Заговор','Desert Eagle - Conspiracy',3,9);
INSERT INTO `Guns` VALUES(123,'Five-SeveN','Птичьи игры','Five-SeveN - Fowl Play',3,9);
INSERT INTO `Guns` VALUES(124,'Glock-18','Водяной','Glock-18 - Water Elemental',3,9);
INSERT INTO `Guns` VALUES(125,'P90','Азимов','P90 - Asiimov',4,9);
INSERT INTO `Guns` VALUES(126,'M4A1-S','Сайрекс','M4A1-S - Cyrex',4,9);
INSERT INTO `Guns` VALUES(127,'Нож-бабочка','','Butterfly Knife',5,9);
INSERT INTO `Guns` VALUES(128,'M4A4','Тусклые полосы','M4A4 - Faded Zebra',1,10);
INSERT INTO `Guns` VALUES(129,'FAMAS','Смертенок','FAMAS - Doomkitty',1,10);
INSERT INTO `Guns` VALUES(130,'MAG-7','Объемные шестиугольники','MAG-7 - Memento',1,10);
INSERT INTO `Guns` VALUES(131,'Sawed-Off','Пиксельный камуфляж «Ржавчина»','Sawed-Off - Orange DDPAT',2,10);
INSERT INTO `Guns` VALUES(132,'P250','Пятно','P250 - Splash',2,10);
INSERT INTO `Guns` VALUES(133,'Galil AR','Пиксельный камуфляж «Ржавчина»','Galil AR - Orange DDPAT',2,10);
INSERT INTO `Guns` VALUES(134,'AK-47','Красный глянец','AK-47 - Red Laminate',3,10);
INSERT INTO `Guns` VALUES(135,'AWP','БАХ','AWP - BOOM',3,10);
INSERT INTO `Guns` VALUES(136,'P90','Смертоносные кошечки','P90 - Death by Kitty',4,10);
INSERT INTO `Guns` VALUES(137,'редкий особый пункт','','Rare Special Item',5,10);
INSERT INTO `Guns` VALUES(138,'Galil AR','Синий титан','Galil AR - Blue Titanium',1,11);
INSERT INTO `Guns` VALUES(139,'Five-SeveN','Паслен','Five-SeveN - Nightshade',1,11);
INSERT INTO `Guns` VALUES(140,'ПП-19 Бизон','Знак воды','PP-Bizon - Water Sigil',1,11);
INSERT INTO `Guns` VALUES(141,'Nova','Призрачный камуфляж','Nova - Ghost Camo',1,11);
INSERT INTO `Guns` VALUES(142,'G3SG1','Лазурная зебра','G3SG1 - Azure Zebra',1,11);
INSERT INTO `Guns` VALUES(143,'P250','Ржавая сталь','P250 - Steel Disruption',1,11);
INSERT INTO `Guns` VALUES(144,'AK-47','Синий ламинат','AK-47 - Blue Laminate',2,11);
INSERT INTO `Guns` VALUES(145,'P90','Слепое пятно','P90 - Blind Spot',2,11);
INSERT INTO `Guns` VALUES(146,'FAMAS','Остаточное изображение','FAMAS - Afterimage',3,11);
INSERT INTO `Guns` VALUES(147,'AWP','Электрический улей','AWP - Electric Hive',3,11);
INSERT INTO `Guns` VALUES(148,'Desert Eagle','Ржавый кобальт','Desert Eagle - Cobalt Disruption',3,11);
INSERT INTO `Guns` VALUES(149,'M4A4','Рентген','M4A4 - X-Ray',4,11);
INSERT INTO `Guns` VALUES(150,'редкий особый пункт','','Rare Special Item',5,11);
INSERT INTO `Guns` VALUES(151,'SSG 08','Темная вода','SSG 08 - Dark Water',1,12);
INSERT INTO `Guns` VALUES(152,'MAC-10','Ультрафиолет','MAC-10 - Ultraviolet',1,12);
INSERT INTO `Guns` VALUES(153,'USP-S','Кровавый тигр','USP-S - Blood Tiger',1,12);
INSERT INTO `Guns` VALUES(154,'CZ75-Auto','Гексан','CZ75-Auto - Hexane',1,12);
INSERT INTO `Guns` VALUES(155,'Negev','Тра-та-та','Negev - Bratatat',1,12);
INSERT INTO `Guns` VALUES(156,'XM1014','Красный питон','XM1014 - Red Python',1,12);
INSERT INTO `Guns` VALUES(157,'ПП-19 Бизон','Синяя струя','PP-Bizon - Blue Streak',2,12);
INSERT INTO `Guns` VALUES(158,'P90','Вирус','P90 - Virus',2,12);
INSERT INTO `Guns` VALUES(159,'MP7','Океанская пена','MP7 - Ocean Foam',2,12);
INSERT INTO `Guns` VALUES(160,'Glock-18','Ржавая сталь','Glock-18 - Steel Disruption',2,12);
INSERT INTO `Guns` VALUES(161,'Desert Eagle','Кровавая паутина','Desert Eagle - Crimson Web',2,12);
INSERT INTO `Guns` VALUES(162,'AUG','Бенгальский тигр','AUG - Bengal Tiger',3,12);
INSERT INTO `Guns` VALUES(163,'Nova','Расцветающая ветка','Nova - Bloomstick',3,12);
INSERT INTO `Guns` VALUES(164,'AWP','Кортисейра','AWP - Corticera',3,12);
INSERT INTO `Guns` VALUES(165,'P2000','Кортисейра','P2000 - Corticera',3,12);
INSERT INTO `Guns` VALUES(166,'M4A4','Дождь из пуль','M4A4 - Bullet Rain',4,12);
INSERT INTO `Guns` VALUES(167,'AK-47','Ягуар','AK-47 - Jaguar',4,12);
INSERT INTO `Guns` VALUES(168,'редкий особый пункт','','Rare Special Item',5,12);
INSERT INTO `Guns` VALUES(169,'Удачные 13','','Lucky 13',1,13);
INSERT INTO `Guns` VALUES(170,'Козырные тузы','','Aces High',1,13);
INSERT INTO `Guns` VALUES(171,'Завоеватель','','I Conquered',1,13);
INSERT INTO `Guns` VALUES(172,'Найти и уничтожить','','Seek & Destroy',1,13);
INSERT INTO `Guns` VALUES(173,'Черный пес','','Black Dog',1,13);
INSERT INTO `Guns` VALUES(174,'Грозный','','Fearsome',1,13);
INSERT INTO `Guns` VALUES(175,'Цербер','','Cerberus',1,13);
INSERT INTO `Guns` VALUES(176,'Плевое дело','','Easy Peasy',1,13);
INSERT INTO `Guns` VALUES(177,'Везунчик','','Luck Skill',1,13);
INSERT INTO `Guns` VALUES(178,'Бдительность','','Vigilance',1,13);
INSERT INTO `Guns` VALUES(179,'Козырные тузы (голографическая)','','Aces High (Holo)',2,13);
INSERT INTO `Guns` VALUES(180,'Грозный (голографическая)','','Fearsome (Holo)',2,13);
INSERT INTO `Guns` VALUES(181,'Бдительность (голографическая)','','Vigilance (Holo)',2,13);
INSERT INTO `Guns` VALUES(182,'Удачные 13 (металлическая)','','Lucky 13 (Foil)',3,13);
INSERT INTO `Guns` VALUES(183,'Везунчик (металлическая)','','Luck Skill (Foil)',3,13);
INSERT INTO `Guns` VALUES(184,'Банан','','Banana',1,14);
INSERT INTO `Guns` VALUES(185,'Код от бомбы','','Bomb Code',1,14);
INSERT INTO `Guns` VALUES(186,'Любитель цыпочек','','Chicken Lover',1,14);
INSERT INTO `Guns` VALUES(187,'Хорошая игра','','Good Game',1,14);
INSERT INTO `Guns` VALUES(188,'Удачи','','Good Luck',1,14);
INSERT INTO `Guns` VALUES(189,'Повеселимся','','Have Fun',1,14);
INSERT INTO `Guns` VALUES(190,'Lets Roll-oll','','Lets Roll-oll',1,14);
INSERT INTO `Guns` VALUES(191,'Металл','','Metal',1,14);
INSERT INTO `Guns` VALUES(192,'Отличный выстрел','','Nice Shot',1,14);
INSERT INTO `Guns` VALUES(193,'Желаю крепкой хватки','','Welcome to the Clutch',1,14);
INSERT INTO `Guns` VALUES(194,'Bish (голографическая)','','Bish (Holo)',2,14);
INSERT INTO `Guns` VALUES(195,'Bash (голографическая)','','Bash (Holo)',2,14);
INSERT INTO `Guns` VALUES(196,'Bosh (голографическая)','','Bosh (Holo)',2,14);
INSERT INTO `Guns` VALUES(197,'Корона (металлическая)','','Crown (Foil)',3,14);
INSERT INTO `Guns` VALUES(198,'Глупый банан (металлическая)','','Stupid Banana (Foil)',3,14);
INSERT INTO `Guns` VALUES(199,'Удар в спину','','Backstab',1,15);
INSERT INTO `Guns` VALUES(200,'Карманный мангал','','Pocket BBQ',1,15);
INSERT INTO `Guns` VALUES(201,'Собака-взрывака','','Bomb Doge',1,15);
INSERT INTO `Guns` VALUES(202,'Сжечь их всех','','Burn Them All',1,15);
INSERT INTO `Guns` VALUES(203,'Лама-пушка','','Llama Cannon',1,15);
INSERT INTO `Guns` VALUES(204,'Запасной AWP','','My Other Awp',1,15);
INSERT INTO `Guns` VALUES(205,'Повелитель лезвия','','Shave Master',1,15);
INSERT INTO `Guns` VALUES(206,'Открытый череп','','Rising Skull',1,15);
INSERT INTO `Guns` VALUES(207,'Тише воды, ниже травы','','Sneaky Beaky Like',1,15);
INSERT INTO `Guns` VALUES(208,'Б или не Б','','To B or not to B',1,15);
INSERT INTO `Guns` VALUES(209,'Смерть идет','','Death Comes',1,15);
INSERT INTO `Guns` VALUES(210,'Командная работа (голографическая)','','Teamwork (Holo)',2,15);
INSERT INTO `Guns` VALUES(211,'Rekt (голографическая)
','','Rekt (Holo)',2,15);
INSERT INTO `Guns` VALUES(212,'Охотник за головами (металлическая)','','Headhunter (Foil)',3,15);
INSERT INTO `Guns` VALUES(213,'Огнеопасно (металлическая)','','Flammable (Foil)',3,15);
INSERT INTO `Guns` VALUES(214,'Новый шериф (металлическая)','','New Sheriff (Foil)',3,15);
INSERT INTO `Guns` VALUES(215,'Круть (металлическая)','','Swag (Foil)',3,15);
INSERT INTO `Guns` VALUES(216,'3DMAX','Катовице 2014','3DMAX - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(217,'iBUYPOWER','Катовице 2014','iBUYPOWER - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(218,'mousesports','Катовице 2014','mousesports - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(219,'Clan-Mystik','Катовице 2014','Clan-Mystik - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(220,'Natus Vincere','Катовице 2014','Natus Vincere - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(221,'Reason Gaming','Катовице 2014','Reason Gaming - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(222,'Virtus.Pro','Катовице 2014','Virtus.Pro - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(223,'Vox Eminor','Катовице 2014','Vox Eminor - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES(224,'3DMAX (голографическая)','Катовице 2014','3DMAX (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(225,'iBUYPOWER (голографическая)','Катовице 2014','iBUYPOWER (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(226,'mousesports (голографическая)','Катовице 2014','mousesports (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(227,'Clan-Mystik (голографическая)','Катовице 2014','Clan-Mystik (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(228,'Natus Vincere (голографическая)','Катовице 2014','Natus Vincere (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(229,'Reason Gaming (голографическая)','Катовице 2014','Reason Gaming (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(230,'Virtus.Pro (голографическая)','Катовице 2014','Virtus.Pro (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(231,'Vox Eminor (голографическая)','Катовице 2014','Vox Eminor (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES(232,'Волк ESL (металлическая)','Катовице 2014','ESL Wolf (Foil) - Katowice 2014',3,16);
INSERT INTO `Guns` VALUES(233,'compLexity Gaming','Катовице 2014','compLexity Gaming - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(234,'Team Dignitas','Катовице 2014','Team Dignitas - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(235,'Fnatic','Катовице 2014','Fnatic - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(236,'HellRaisers','Катовице 2014','HellRaisers - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(237,'Team LDLC.com','Катовице 2014','Team LDLC.com - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(238,'LGB eSports','Катовице 2014','LGB eSports - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(239,'Ninjas in Pyjamas','Катовице 2014','Ninjas in Pyjamas - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(240,'Titan','Катовице 2014','Titan - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES(241,'compLexity Gaming (голографическая)','Катовице 2014','compLexity Gaming (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(242,'Team Dignitas (голографическая)','Катовице 2014','Team Dignitas (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(243,'Fnatic (голографическая)','Катовице 2014','Fnatic (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(244,'HellRaisers (голографическая)','Катовице 2014','HellRaisers (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(245,'Team LDLC.com (голографическая)','Катовице 2014','Team LDLC.com (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(246,'LGB eSports (голографическая)','Катовице 2014','LGB eSports (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(247,'Ninjas in Pyjamas (голографическая)','Катовице 2014','Ninjas in Pyjamas (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(248,'Titan (голографическая)','Катовице 2014','Titan (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES(249,'Череп ESL (металлическая)','Катовице 2014','ESL Skull (Foil) - Katowice 2014',3,17);
INSERT INTO `Guns` VALUES(250,'Copenhagen Wolves','Кёльн 2014','Copenhagen Wolves - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(251,'dAT team','Кёльн 2014','dAT team - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(252,'Epsilon eSports','Кёльн 2014','Epsilon eSports - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(253,'iBUYPOWER','Кёльн 2014','iBUYPOWER - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(254,'London Conspiracy','Кёльн 2014','London Conspiracy - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(255,'Natus Vincere','Кёльн 2014','Natus Vincere - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(256,'Titan','Кёльн 2014','Titan - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(257,'Vox Eminor','Кёльн 2014','Vox Eminor - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(258,'MTS GameGod Wolf','Кёльн 2014','MTS GameGod Wolf - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES(259,'Copenhagen Wolves (голографическая)','Кёльн 2014','Copenhagen Wolves (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(260,'dAT team (голографическая)','Кёльн 2014','dAT team (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(261,'Epsilon eSports (голографическая)','Кёльн 2014','Epsilon eSports (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(262,'iBUYPOWER (голографическая)','Кёльн 2014','iBUYPOWER (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(263,'London Conspiracy (голографическая)','Кёльн 2014','London Conspiracy (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(264,'Natus Vincere (голографическая)','Кёльн 2014','Natus Vincere (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(265,'Titan (голографическая)','Кёльн 2014','Titan (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(266,'Vox Eminor (голографическая)','Кёльн 2014','Vox Eminor (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(267,'MTS GameGod Wolf (голографическая)','Кёльн 2014','MTS GameGod Wolf (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES(268,'ESL One Cologne 2014 (красная)','','ESL One Cologne 2014 (Red)',3,18);
INSERT INTO `Guns` VALUES(269,'Cloud9','Кёльн 2014','Cloud9 - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES(270,'Fnatic','Кёльн 2014','Fnatic - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES(271,'HellRaisers','Кёльн 2014','HellRaisers - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES(272,'Ninjas in Pyjamas','Кёльн 2014','Ninjas in Pyjamas - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES(273,'Team Dignitas','Кёльн 2014','Team Dignitas - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES(274,'Team LDLC.com','Кёльн 2014','Team LDLC.com - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES(275,'Virtus.Pro','Кёльн 2014','Virtus.Pro - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES(276,'Cloud9 (Holo)','Кёльн 2014','Cloud9 (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES(277,'Fnatic (Holo)','Кёльн 2014','Fnatic (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES(278,'HellRaisers (Holo)','Кёльн 2014','HellRaisers (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES(279,'Ninjas in Pyjamas (Holo)','Кёльн 2014','Ninjas in Pyjamas (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES(280,'Team Dignitas (Holo)','Кёльн 2014','Team Dignitas (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES(281,'Team LDLC.com (Holo)','Кёльн 2014','Team LDLC.com (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES(282,'Virtus.Pro (Holo)','Кёльн 2014','Virtus.Pro (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES(283,'ESL One Cologne 2014 (синяя)','','ESL One Cologne 2014 (Blue)',3,19);
INSERT INTO `Guns` VALUES(284,'G3SG1','Мрак','G3SG1 - Murky',1,20);
INSERT INTO `Guns` VALUES(285,'MAG-7','Поджигатель','MAG-7 - Firestarter',1,20);
INSERT INTO `Guns` VALUES(286,'MP9','Дротик','MP9 - Dart',1,20);
INSERT INTO `Guns` VALUES(287,'Five-SeveN','Городская опасность','Five-SeveN - Urban Hazard',1,20);
INSERT INTO `Guns` VALUES(288,'UMP-45','Заблуждение','UMP-45 - Delusion',1,20);
INSERT INTO `Guns` VALUES(289,'Glock-18','Жернов','Glock-18 - Grinder',2,20);
INSERT INTO `Guns` VALUES(290,'M4A1-S','Василиск','M4A1-S - Basilisk',2,20);
INSERT INTO `Guns` VALUES(291,'M4A4','Грифон','M4A4 - Griffin',2,20);
INSERT INTO `Guns` VALUES(292,'Sawed-Off','Разбойник','Sawed-Off - Highwayman',2,20);
INSERT INTO `Guns` VALUES(293,'P250','Картель','P250 - Cartel',3,20);
INSERT INTO `Guns` VALUES(294,'SCAR-20','Кардио','SCAR-20 - Cardiac',3,20);
INSERT INTO `Guns` VALUES(295,'XM1014','Спокойствие','XM1014 - Tranquility',3,20);
INSERT INTO `Guns` VALUES(296,'AK-47','Пустынный повстанец','AK-47 - Wasteland Rebel',4,20);
INSERT INTO `Guns` VALUES(297,'P2000','Огненный элементаль','P2000 - Fire Elemental',4,20);
INSERT INTO `Guns` VALUES(298,'редкий особый пункт','','Rare Special Item',5,20);
INSERT INTO `Guns` VALUES(299,'Glock-18','Катакомбы','Glock-18 - Catacombs',1,21);
INSERT INTO `Guns` VALUES(300,'M249','система блокировки','M249 - System Lock',1,21);
INSERT INTO `Guns` VALUES(301,'MP9','Смертельный яд','MP9 - Deadly Poison',1,21);
INSERT INTO `Guns` VALUES(302,'SCAR-20','грот','SCAR-20 - Grotto',1,21);
INSERT INTO `Guns` VALUES(303,'XM1014','ртуть','XM1014 - Quicksilver',1,21);
INSERT INTO `Guns` VALUES(304,'Dual Berettas','Городской шок','Dual Berettas - Urban Shock',2,21);
INSERT INTO `Guns` VALUES(305,'Desert Eagle','дракон','Desert Eagle - Naga',2,21);
INSERT INTO `Guns` VALUES(306,'MAC-10','малахит','MAC-10 - Malachite',2,21);
INSERT INTO `Guns` VALUES(307,'Sawed-Off','спокойствие','Sawed-Off - Serenity',2,21);
INSERT INTO `Guns` VALUES(308,'AK-47','картель','AK-47 - Cartel',3,21);
INSERT INTO `Guns` VALUES(309,'M4A4','короля Дракона','M4A4 - Dragon King',3,21);
INSERT INTO `Guns` VALUES(310,'P250','Muertos','P250 - Muertos',3,21);
INSERT INTO `Guns` VALUES(311,'AWP','Человек блуждающий война','AWP - Man-o''-war',4,21);
INSERT INTO `Guns` VALUES(312,'Galil AR','болтун','Galil AR - Chatterbox',4,21);
INSERT INTO `Guns` VALUES(313,'редкий особый пункт','','Rare Special Item',5,21);
INSERT INTO `Guns` VALUES(314,'редкий особый пункт','','Rare Special Item',5,3);
INSERT INTO `Guns` VALUES(315,'редкий особый пункт','','Rare Special Item',5,4);
CREATE TABLE "EventStickers" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`evStickType`	TEXT,
	`evStickSkin`	TEXT,
	`evStickTexture`	TEXT NOT NULL,
	`rarity`	TEXT NOT NULL,
	`spawnRarity`	TEXT NOT NULL,
	`startDate`	TEXT NOT NULL,
	`endDate`	TEXT NOT NULL
);
INSERT INTO `EventStickers` VALUES(1,'рождество',2014,'Christmas - 2014',2,2,'11 12 2014','30 12 2014');
INSERT INTO `EventStickers` VALUES(2,'Новый год',2015,'New Years - 2015',2,2,'24 12 2014 ','07 01 2015');
CREATE TABLE "Cases" (
	`_id`	INTEGER NOT NULL,
	`caseName`	TEXT NOT NULL,
	`caseTexture`	TEXT NOT NULL,
	`price`	INTEGER NOT NULL
);
INSERT INTO `Cases` VALUES(1,'Оружейный кейс 1','CSGO 1',0);
INSERT INTO `Cases` VALUES(2,'Оружейный кейс 2','CSGO 2',0);
INSERT INTO `Cases` VALUES(3,'Оружейный кейс 3','CSGO 3',0);
INSERT INTO `Cases` VALUES(4,'Кейс операции «Браво»','Operation Bravo',0);
INSERT INTO `Cases` VALUES(5,'кейс «Winter Offensive»','Winter Offensive',0);
INSERT INTO `Cases` VALUES(6,'кейс операции «Феникс»','Operation Phoenix',0);
INSERT INTO `Cases` VALUES(7,'Охотничий кейс (старый)','Huntsman',0);
INSERT INTO `Cases` VALUES(8,'Охотничий кейс (новый)','Huntsman',0);
INSERT INTO `Cases` VALUES(9,'кейс операции «Прорыв»','Operation Breakout',0);
INSERT INTO `Cases` VALUES(20,'кейс операции «Авангард»','Operation Vanguard',0);
INSERT INTO `Cases` VALUES(21,'Chroma Case','Chroma',0);
INSERT INTO `Cases` VALUES(10,'Кейс eSports 2013','eSports 2013',0);
INSERT INTO `Cases` VALUES(11,'Зимний кейс eSports 2013','eSports 2013 Winter',0);
INSERT INTO `Cases` VALUES(12,'Летний кейс eSports 2014','eSports 2014 Summer',0);
INSERT INTO `Cases` VALUES(13,'Капсула с наклейкой 1','Sticker 1',0);
INSERT INTO `Cases` VALUES(14,'Капсула с наклейкой 2','Sticker 2',0);
INSERT INTO `Cases` VALUES(15,'Капсула с наклейкой сообщества 1','Community Sticker 1',0);
INSERT INTO `Cases` VALUES(16,'Претенденты EMS Katowice 2014','EMS Katowice 2014 Challengers',0);
INSERT INTO `Cases` VALUES(17,'Легенды EMS Katowice 2014','EMS Katowice 2014 Legends',0);
INSERT INTO `Cases` VALUES(18,'Претенденты ESL One Cologne 2014','ESL One Cologne 2014 Challengers',0);
INSERT INTO `Cases` VALUES(19,'Легенды ESL One Cologne 2014','ESL One Cologne 2014 Legends',0);