CREATE TABLE "Knives" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`knifeType`	TEXT,
	`knifeSkin`	TEXT,
	`knifeTexture`	TEXT NOT NULL,
	`knifeID`	INTEGER NOT NULL
);
INSERT INTO `Knives` VALUES (1,'Bayonet','','Bayonet',1);
INSERT INTO `Knives` VALUES (2,'Bayonet','Boreal Forest','Bayonet - Boreal Forest',1);
INSERT INTO `Knives` VALUES (3,'Bayonet','Case Hardened','Bayonet - Case Hardened',1);
INSERT INTO `Knives` VALUES (4,'Bayonet','Crimson Web','Bayonet - Crimson Web',1);
INSERT INTO `Knives` VALUES (5,'Bayonet','Fade','Bayonet - Fade',1);
INSERT INTO `Knives` VALUES (6,'Bayonet','Forest DDPAT','Bayonet - Forest DDPAT',1);
INSERT INTO `Knives` VALUES (7,'Bayonet','Night','Bayonet - Night',1);
INSERT INTO `Knives` VALUES (8,'Bayonet','Safari Mesh','Bayonet - Safari Mesh',1);
INSERT INTO `Knives` VALUES (9,'Bayonet','Scorched','Bayonet - Scorched',1);
INSERT INTO `Knives` VALUES (10,'Bayonet','Slaughter','Bayonet - Slaughter',1);
INSERT INTO `Knives` VALUES (11,'Bayonet','Stained','Bayonet - Stained',1);
INSERT INTO `Knives` VALUES (12,'Bayonet','Urban Masked','Bayonet - Urban Masked',1);
INSERT INTO `Knives` VALUES (13,'Flip Knife','','Flip Knife',2);
INSERT INTO `Knives` VALUES (14,'Flip Knife','Boreal Forest','Flip Knife - Boreal Forest',2);
INSERT INTO `Knives` VALUES (15,'Flip Knife','Case Hardened','Flip Knife - Case Hardened',2);
INSERT INTO `Knives` VALUES (16,'Flip Knife','Crimson Web','Flip Knife - Crimson Web',2);
INSERT INTO `Knives` VALUES (17,'Flip Knife','Fade','Flip Knife - Fade',2);
INSERT INTO `Knives` VALUES (18,'Flip Knife','Forest DDPAT','Flip Knife - Forest DDPAT',2);
INSERT INTO `Knives` VALUES (19,'Flip Knife','Night','Flip Knife - Night',2);
INSERT INTO `Knives` VALUES (20,'Flip Knife','Safari Mesh','Flip Knife - Safari Mesh',2);
INSERT INTO `Knives` VALUES (21,'Flip Knife','Scorched','Flip Knife - Scorched',2);
INSERT INTO `Knives` VALUES (22,'Flip Knife','Slaughter','Flip Knife - Slaughter',2);
INSERT INTO `Knives` VALUES (23,'Flip Knife','Stained','Flip Knife - Stained',2);
INSERT INTO `Knives` VALUES (24,'Flip Knife','Urban Masked','Flip Knife - Urban Masked',2);
INSERT INTO `Knives` VALUES (25,'Gut Knife','','Gut Knife',3);
INSERT INTO `Knives` VALUES (26,'Gut Knife','Blue Steel','Gut Knife - Blue Steel',3);
INSERT INTO `Knives` VALUES (27,'Gut Knife','Boreal Forest','Gut Knife - Boreal Forest',3);
INSERT INTO `Knives` VALUES (28,'Gut Knife','Case Hardened','Gut Knife - Case Hardened',3);
INSERT INTO `Knives` VALUES (29,'Gut Knife','Crimson Web','Gut Knife - Crimson Web',3);
INSERT INTO `Knives` VALUES (30,'Gut Knife','Fade','Gut Knife - Fade',3);
INSERT INTO `Knives` VALUES (31,'Gut Knife','Forest DDPAT','Gut Knife - Forest DDPAT',3);
INSERT INTO `Knives` VALUES (32,'Gut Knife','Night','Gut Knife - Night',3);
INSERT INTO `Knives` VALUES (33,'Gut Knife','Safari Mesh','Gut Knife - Safari Mesh',3);
INSERT INTO `Knives` VALUES (34,'Gut Knife','Scorched','Gut Knife - Scorched',3);
INSERT INTO `Knives` VALUES (35,'Gut Knife','Slaughter','Gut Knife - Slaughter',3);
INSERT INTO `Knives` VALUES (36,'Gut Knife','Stained','Gut Knife - Stained',3);
INSERT INTO `Knives` VALUES (37,'Gut Knife','Urban Masked','Gut Knife - Urban Masked',3);
INSERT INTO `Knives` VALUES (38,'Huntsman Knife','','Huntsman Knife',4);
INSERT INTO `Knives` VALUES (39,'Huntsman Knife','Blue Steel','Huntsman Knife - Blue Steel',4);
INSERT INTO `Knives` VALUES (40,'Huntsman Knife','Boreal Forest','Huntsman Knife - Boreal Forest',4);
INSERT INTO `Knives` VALUES (41,'Huntsman Knife','Case Hardened','Huntsman Knife - Case Hardened',4);
INSERT INTO `Knives` VALUES (42,'Huntsman Knife','Crimson Web','Huntsman Knife - Crimson Web',4);
INSERT INTO `Knives` VALUES (43,'Huntsman Knife','Fade','Huntsman Knife - Fade',4);
INSERT INTO `Knives` VALUES (44,'Huntsman Knife','Forest DDPAT','Huntsman Knife - Forest DDPAT',4);
INSERT INTO `Knives` VALUES (45,'Huntsman Knife','Night','Huntsman Knife - Night',4);
INSERT INTO `Knives` VALUES (46,'Huntsman Knife','Safari Mesh','Huntsman Knife - Safari Mesh',4);
INSERT INTO `Knives` VALUES (47,'Huntsman Knife','Scorched','Huntsman Knife - Scorched',4);
INSERT INTO `Knives` VALUES (48,'Huntsman Knife','Slaughter','Huntsman Knife - Slaughter',4);
INSERT INTO `Knives` VALUES (49,'Huntsman Knife','Stained','Huntsman Knife - Stained',4);
INSERT INTO `Knives` VALUES (50,'Huntsman Knife','Urban Masked','Huntsman Knife - Urban Masked',4);
INSERT INTO `Knives` VALUES (51,'Karambit','','Karambit',5);
INSERT INTO `Knives` VALUES (52,'Karambit','Blue Steel','Karambit - Blue Steel',5);
INSERT INTO `Knives` VALUES (53,'Karambit','Boreal Forest','Karambit - Boreal Forest',5);
INSERT INTO `Knives` VALUES (54,'Karambit','Case Hardened','Karambit - Case Hardened',5);
INSERT INTO `Knives` VALUES (55,'Karambit','Fade','Karambit - Fade',5);
INSERT INTO `Knives` VALUES (56,'Karambit','Night','Karambit - Night',5);
INSERT INTO `Knives` VALUES (57,'Karambit','Scorched','Karambit - Scorched',5);
INSERT INTO `Knives` VALUES (58,'Karambit','Slaughter','Karambit - Slaughter',5);
INSERT INTO `Knives` VALUES (59,'Karambit','Stained','Karambit - Stained',5);
INSERT INTO `Knives` VALUES (60,'Karambit','Urban Masked','Karambit - Urban Masked',5);
INSERT INTO `Knives` VALUES (61,'M9 Bayonet','','M9 Bayonet',6);
INSERT INTO `Knives` VALUES (62,'M9 Bayonet','Blue Steel','M9 Bayonet - Blue Steel',6);
INSERT INTO `Knives` VALUES (63,'M9 Bayonet','Boreal Forest','M9 Bayonet - Boreal Forest',6);
INSERT INTO `Knives` VALUES (64,'M9 Bayonet','Case Hardened','M9 Bayonet - Case Hardened',6);
INSERT INTO `Knives` VALUES (65,'M9 Bayonet','Crimson Web','M9 Bayonet - Crimson Web',6);
INSERT INTO `Knives` VALUES (66,'M9 Bayonet','Fade','M9 Bayonet - Fade',6);
INSERT INTO `Knives` VALUES (67,'M9 Bayonet','Forest DDPAT','M9 Bayonet - Forest DDPAT',6);
INSERT INTO `Knives` VALUES (68,'M9 Bayonet','Night','M9 Bayonet - Night',6);
INSERT INTO `Knives` VALUES (69,'M9 Bayonet','Safari Mesh','M9 Bayonet - Safari Mesh',6);
INSERT INTO `Knives` VALUES (70,'M9 Bayonet','Scorched','M9 Bayonet - Scorched',6);
INSERT INTO `Knives` VALUES (71,'M9 Bayonet','Slaughter','M9 Bayonet - Slaughter',6);
INSERT INTO `Knives` VALUES (72,'M9 Bayonet','Stained','M9 Bayonet - Stained',6);
INSERT INTO `Knives` VALUES (73,'M9 Bayonet','Urban Masked','M9 Bayonet - Urban Masked',6);
INSERT INTO `Knives` VALUES (74,'Butterfly Knife','','Butterfly Knife',7);
INSERT INTO `Knives` VALUES (75,'Butterfly Knife','Blue Steel','Butterfly Knife - Blue Steel',7);
INSERT INTO `Knives` VALUES (76,'Butterfly Knife','Boreal Forest','Butterfly Knife - Boreal Forest',7);
INSERT INTO `Knives` VALUES (77,'Butterfly Knife','Case Hardened','Butterfly Knife - Case Hardened',7);
INSERT INTO `Knives` VALUES (78,'Butterfly Knife','Crimson Web','Butterfly Knife - Crimson Web',7);
INSERT INTO `Knives` VALUES (79,'Butterfly Knife','Fade','Butterfly Knife - Fade',7);
INSERT INTO `Knives` VALUES (80,'Butterfly Knife','Forest DDPAT','Butterfly Knife - Forest DDPAT',7);
INSERT INTO `Knives` VALUES (81,'Butterfly Knife','Night','Butterfly Knife - Night',7);
INSERT INTO `Knives` VALUES (82,'Butterfly Knife','Safari Mesh','Butterfly Knife - Safari Mesh',7);
INSERT INTO `Knives` VALUES (83,'Butterfly Knife','Scorched','Butterfly Knife - Scorched',7);
INSERT INTO `Knives` VALUES (84,'Butterfly Knife','Slaughter','Butterfly Knife - Slaughter',7);
INSERT INTO `Knives` VALUES (85,'Butterfly Knife','Stained','Butterfly Knife - Stained',7);
INSERT INTO `Knives` VALUES (86,'Butterfly Knife','Urban Masked','Butterfly Knife - Urban Masked',7);
INSERT INTO `Knives` VALUES (87,'Bayonet','Damascus Steel','Bayonet - Damascus Steel',8);
INSERT INTO `Knives` VALUES (88,'Bayonet','Doppler','Bayonet - Doppler',8);
INSERT INTO `Knives` VALUES (89,'Bayonet','Marble Fade','Bayonet - Marble Fade',8);
INSERT INTO `Knives` VALUES (90,'Bayonet','Rust Coat','Bayonet - Rust Coat',8);
INSERT INTO `Knives` VALUES (91,'Bayonet','Tiger Tooth','Bayonet - Tiger Tooth',8);
INSERT INTO `Knives` VALUES (92,'Flip Knife','Damascus Steel','Flip Knife - Damascus Steel',8);
INSERT INTO `Knives` VALUES (93,'Flip Knife','Doppler','Flip Knife - Doppler',8);
INSERT INTO `Knives` VALUES (94,'Flip Knife','Marble Fade','Flip Knife - Marble Fade',8);
INSERT INTO `Knives` VALUES (95,'Flip Knife','Rust Coat','Flip Knife - Rust Coat',8);
INSERT INTO `Knives` VALUES (96,'Flip Knife','Tiger Tooth','Flip Knife - Tiger Tooth',8);
INSERT INTO `Knives` VALUES (97,'Gut Knife','Damascus Steel','Gut Knife - Damascus Steel',8);
INSERT INTO `Knives` VALUES (98,'Gut Knife','Doppler','Gut Knife - Doppler',8);
INSERT INTO `Knives` VALUES (99,'Gut Knife','Marble Fade','Gut Knife - Marble Fade',8);
INSERT INTO `Knives` VALUES (100,'Gut Knife','Rust Coat','Gut Knife - Rust Coat',8);
INSERT INTO `Knives` VALUES (101,'Gut Knife','Tiger Tooth','Gut Knife - Tiger Tooth',8);
INSERT INTO `Knives` VALUES (102,'Karambit','Damascus Steel','Karambit - Damascus Steel',8);
INSERT INTO `Knives` VALUES (103,'Karambit','Doppler','Karambit - Doppler',8);
INSERT INTO `Knives` VALUES (104,'Karambit','Marble Fade','Karambit - Marble Fade',8);
INSERT INTO `Knives` VALUES (105,'Karambit','Rust Coat','Karambit - Rust Coat',8);
INSERT INTO `Knives` VALUES (106,'Karambit','Tiger Tooth','Karambit - Tiger Tooth',8);
INSERT INTO `Knives` VALUES (107,'M9 Bayonet','Damascus Steel','M9 Bayonet - Damascus Steel',8);
INSERT INTO `Knives` VALUES (108,'M9 Bayonet','Doppler','M9 Bayonet - Doppler',8);
INSERT INTO `Knives` VALUES (109,'M9 Bayonet','Marble Fade','M9 Bayonet - Marble Fade',8);
INSERT INTO `Knives` VALUES (110,'M9 Bayonet','Rust Coat','M9 Bayonet - Rust Coat',8);
INSERT INTO `Knives` VALUES (111,'M9 Bayonet','Tiger Tooth','M9 Bayonet - Tiger Tooth',8);
INSERT INTO `Knives` VALUES (112,'Falchion Knife','','Falchion Knife',9);
INSERT INTO `Knives` VALUES (113,'Falchion Knife','Blue Steel','Falchion Knife - Blue Steel',9);
INSERT INTO `Knives` VALUES (114,'Falchion Knife','Boreal Forest','Falchion Knife - Boreal Forest',9);
INSERT INTO `Knives` VALUES (115,'Falchion Knife','Case Hardened','Falchion Knife - Case Hardened',9);
INSERT INTO `Knives` VALUES (116,'Falchion Knife','Crimson Web','Falchion Knife - Crimson Web',9);
INSERT INTO `Knives` VALUES (117,'Falchion Knife','Fade','Falchion Knife - Fade',9);
INSERT INTO `Knives` VALUES (118,'Falchion Knife','Forest DDPAT','Falchion Knife - Forest DDPAT',9);
INSERT INTO `Knives` VALUES (119,'Falchion Knife','Night','Falchion Knife - Night',9);
INSERT INTO `Knives` VALUES (120,'Falchion Knife','Safari Mesh','Falchion Knife - Safari Mesh',9);
INSERT INTO `Knives` VALUES (121,'Falchion Knife','Scorched','Falchion Knife - Scorched',9);
INSERT INTO `Knives` VALUES (122,'Falchion Knife','Slaughter','Falchion Knife - Slaughter',9);
INSERT INTO `Knives` VALUES (123,'Falchion Knife','Stained','Falchion Knife - Stained',9);
INSERT INTO `Knives` VALUES (124,'Falchion Knife','Urban Masked','Falchion Knife - Urban Masked',9);
INSERT INTO `Knives` VALUES (125,'Shadow Daggers','','Shadow Daggers',10);
INSERT INTO `Knives` VALUES (126,'Shadow Daggers','Blue Steel','Shadow Daggers - Blue Steel',10);
INSERT INTO `Knives` VALUES (127,'Shadow Daggers','Boreal Forest','Shadow Daggers - Boreal Forest',10);
INSERT INTO `Knives` VALUES (128,'Shadow Daggers','Case Hardened','Shadow Daggers - Case Hardened',10);
INSERT INTO `Knives` VALUES (129,'Shadow Daggers','Crimson Web','Shadow Daggers - Crimson Web',10);
INSERT INTO `Knives` VALUES (130,'Shadow Daggers','Fade','Shadow Daggers - Fade',10);
INSERT INTO `Knives` VALUES (131,'Shadow Daggers','Forest DDPAT','Shadow Daggers - Forest DDPAT',10);
INSERT INTO `Knives` VALUES (132,'Shadow Daggers','Night','Shadow Daggers - Night',10);
INSERT INTO `Knives` VALUES (133,'Shadow Daggers','Safari Mesh','Shadow Daggers - Safari Mesh',10);
INSERT INTO `Knives` VALUES (134,'Shadow Daggers','Scorched','Shadow Daggers - Scorched',10);
INSERT INTO `Knives` VALUES (135,'Shadow Daggers','Slaughter','Shadow Daggers - Slaughter',10);
INSERT INTO `Knives` VALUES (136,'Shadow Daggers','Stained','Shadow Daggers - Stained',10);
INSERT INTO `Knives` VALUES (137,'Shadow Daggers','Urban Masked','Shadow Daggers - Urban Masked',10);
CREATE TABLE "Guns" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`gunType`	TEXT,
	`gunSkin`	TEXT,
	`gunTexture`	TEXT NOT NULL,
	`rarity`	INTEGER NOT NULL,
	`caseID`	INTEGER NOT NULL
);
INSERT INTO `Guns` VALUES (1,'MP7','Skulls','MP7 - Skulls',1,1);
INSERT INTO `Guns` VALUES (2,'SG 553','Ultraviolet','SG 553 - Ultraviolet',1,1);
INSERT INTO `Guns` VALUES (3,'AUG','Wings','AUG - Wings',1,1);
INSERT INTO `Guns` VALUES (4,'M4A1-S','Dark Water','M4A1-S - Dark Water',2,1);
INSERT INTO `Guns` VALUES (5,'USP-S','Dark Water','USP-S - Dark Water',2,1);
INSERT INTO `Guns` VALUES (6,'Glock-18','Dragon Tattoo','Glock-18 - Dragon Tattoo',2,1);
INSERT INTO `Guns` VALUES (7,'Desert Eagle','Hypnotic','Desert Eagle - Hypnotic',3,1);
INSERT INTO `Guns` VALUES (8,'AK-47','Case Hardened','AK-47 - Case Hardened',3,1);
INSERT INTO `Guns` VALUES (9,'AWP','Lightning Strike','AWP - Lightning Strike',4,1);
INSERT INTO `Guns` VALUES (10,'Rare Special Item','','Rare Special Item',5,1);
INSERT INTO `Guns` VALUES (11,'Tec-9','Blue Titanium','Tec-9 - Blue Titanium',1,2);
INSERT INTO `Guns` VALUES (12,'M4A1-S','Blood Tiger','M4A1-S - Blood Tiger',1,2);
INSERT INTO `Guns` VALUES (13,'FAMAS','Hexane','FAMAS - Hexane',1,2);
INSERT INTO `Guns` VALUES (14,'P250','Hive','P250 - Hive',1,2);
INSERT INTO `Guns` VALUES (15,'SCAR-20','Crimson Web','SCAR-20 - Crimson Web',1,2);
INSERT INTO `Guns` VALUES (16,'Five-SeveN','Case Hardened','Five-SeveN - Case Hardened',2,2);
INSERT INTO `Guns` VALUES (17,'MP9','Hypnotic','MP9 - Hypnotic',2,2);
INSERT INTO `Guns` VALUES (18,'Nova','Graphite','Nova - Graphite',2,2);
INSERT INTO `Guns` VALUES (19,'Dual Berettas','Hemoglobin','Dual Berettas - Hemoglobin',2,2);
INSERT INTO `Guns` VALUES (20,'P90','Cold Blooded','P90 - Cold Blooded',3,2);
INSERT INTO `Guns` VALUES (21,'USP-S','Serum','USP-S - Serum',3,2);
INSERT INTO `Guns` VALUES (22,'SSG 08','Blood in the Water','SSG 08 - Blood in the Water',4,2);
INSERT INTO `Guns` VALUES (23,'Rare Special Item','','Rare Special Item',5,2);
INSERT INTO `Guns` VALUES (24,'CZ75-Auto','Crimson Web','CZ75-Auto - Crimson Web',1,3);
INSERT INTO `Guns` VALUES (25,'P2000','Red FragCam','P2000 - Red FragCam',1,3);
INSERT INTO `Guns` VALUES (26,'Dual Berettas','Panther','Dual Berettas - Panther',1,3);
INSERT INTO `Guns` VALUES (27,'USP-S','Stainless','USP-S - Stainless',1,3);
INSERT INTO `Guns` VALUES (28,'Glock-18','Blue Fissure','Glock-18 - Blue Fissure',1,3);
INSERT INTO `Guns` VALUES (29,'CZ75-Auto','Tread Plate','CZ75-Auto - Tread Plate',2,3);
INSERT INTO `Guns` VALUES (30,'Tec-9','Titanium Bit','Tec-9 - Titanium Bit',2,3);
INSERT INTO `Guns` VALUES (31,'Desert Eagle','Heirloom','Desert Eagle - Heirloom',2,3);
INSERT INTO `Guns` VALUES (32,'Five-SeveN','Copper Galaxy','Five-SeveN - Copper Galaxy',2,3);
INSERT INTO `Guns` VALUES (33,'CZ75-Auto','The Fuschia Is Now','CZ75-Auto - The Fuschia Is Now',3,3);
INSERT INTO `Guns` VALUES (34,'P250','Undertow','P250 - Undertow',3,3);
INSERT INTO `Guns` VALUES (35,'CZ75-Auto','Victoria','CZ75-Auto - Victoria',4,3);
INSERT INTO `Guns` VALUES (38,'Nova','Tempest','Nova - Tempest',1,4);
INSERT INTO `Guns` VALUES (39,'Dual Berettas','Black Limba','Dual Berettas - Black Limba',1,4);
INSERT INTO `Guns` VALUES (40,'UMP-45','Bone Pile','UMP-45 - Bone Pile',1,4);
INSERT INTO `Guns` VALUES (41,'SG 553','Wave Spray','SG 553 - Wave Spray',1,4);
INSERT INTO `Guns` VALUES (42,'Galil AR','Shattered','Galil AR - Shattered',1,4);
INSERT INTO `Guns` VALUES (43,'G3SG1','Demeter','G3SG1 - Demeter',1,4);
INSERT INTO `Guns` VALUES (44,'M4A1-S','Bright Water','M4A1-S - Bright Water',2,4);
INSERT INTO `Guns` VALUES (45,'M4A4','Zirka','M4A4 - Zirka',2,4);
INSERT INTO `Guns` VALUES (46,'MAC-10','Graven','MAC-10 - Graven',2,4);
INSERT INTO `Guns` VALUES (47,'USP-S','Overgrowth','USP-S - Overgrowth',2,4);
INSERT INTO `Guns` VALUES (48,'P90','Emerald Dragon','P90 - Emerald Dragon',3,4);
INSERT INTO `Guns` VALUES (49,'P2000','Ocean Foam','P2000 - Ocean Foam',3,4);
INSERT INTO `Guns` VALUES (50,'AWP','Graphite','AWP - Graphite',3,4);
INSERT INTO `Guns` VALUES (51,'Desert Eagle','Golden Koi','Desert Eagle - Golden Koi',4,4);
INSERT INTO `Guns` VALUES (52,'AK-47','Fire Serpent','AK-47 - Fire Serpent',4,4);
INSERT INTO `Guns` VALUES (53,'PP-Bizon','Cobalt Halftone','PP-Bizon - Cobalt Halftone',1,5);
INSERT INTO `Guns` VALUES (54,'M249','Magma','M249 - Magma',1,5);
INSERT INTO `Guns` VALUES (55,'Five-SeveN','Kami','Five-SeveN - Kami',1,5);
INSERT INTO `Guns` VALUES (56,'Galil AR','Sandstorm','Galil AR - Sandstorm',1,5);
INSERT INTO `Guns` VALUES (57,'Nova','Rising Skull','Nova - Rising Skull',2,5);
INSERT INTO `Guns` VALUES (58,'MP9','Rose Iron','MP9 - Rose Iron',2,5);
INSERT INTO `Guns` VALUES (59,'Dual Berettas','Marina','Dual Berettas - Marina',2,5);
INSERT INTO `Guns` VALUES (60,'FAMAS','Pulse','FAMAS - Pulse',2,5);
INSERT INTO `Guns` VALUES (61,'AWP','Redline','AWP - Redline',3,5);
INSERT INTO `Guns` VALUES (62,'P250','Mehndi','P250 - Mehndi',3,5);
INSERT INTO `Guns` VALUES (63,'M4A1-S','Guardian','M4A1-S - Guardian',3,5);
INSERT INTO `Guns` VALUES (64,'Sawed-Off','The Kraken','Sawed-Off - The Kraken',4,5);
INSERT INTO `Guns` VALUES (65,'M4A4','Asiimov','M4A4 - Asiimov',4,5);
INSERT INTO `Guns` VALUES (66,'Rare Special Item','','Rare Special Item',5,5);
INSERT INTO `Guns` VALUES (67,'UMP-45','Corporal','UMP-45 - Corporal',1,6);
INSERT INTO `Guns` VALUES (68,'Negev','Terrain','Negev - Terrain',1,6);
INSERT INTO `Guns` VALUES (69,'Tec-9','Sandstorm','Tec-9 - Sandstorm',1,6);
INSERT INTO `Guns` VALUES (70,'MAG-7','Heaven Guard','MAG-7 - Heaven Guard',1,6);
INSERT INTO `Guns` VALUES (71,'MAC-10','Heat','MAC-10 - Heat',2,6);
INSERT INTO `Guns` VALUES (72,'SG 553','Pulse','SG 553 - Pulse',2,6);
INSERT INTO `Guns` VALUES (73,'FAMAS','Sergeant','FAMAS - Sergeant',2,6);
INSERT INTO `Guns` VALUES (74,'USP-S','Guardian','USP-S - Guardian',2,6);
INSERT INTO `Guns` VALUES (75,'AK-47','Redline','AK-47 - Redline',3,6);
INSERT INTO `Guns` VALUES (76,'P90','Trigon','P90 - Trigon',3,6);
INSERT INTO `Guns` VALUES (77,'Nova','Antique','Nova - Antique',3,6);
INSERT INTO `Guns` VALUES (78,'AWP','Asiimov','AWP - Asiimov',4,6);
INSERT INTO `Guns` VALUES (79,'AUG','Chameleon','AUG - Chameleon',4,6);
INSERT INTO `Guns` VALUES (80,'Rare Special Item','','Rare Special Item',5,6);
INSERT INTO `Guns` VALUES (81,'Tec-9','Isaac','Tec-9 - Isaac',1,7);
INSERT INTO `Guns` VALUES (82,'SSG 08','Slashed','SSG 08 - Slashed',1,7);
INSERT INTO `Guns` VALUES (83,'Dual Berettas','Retribution','Dual Berettas - Retribution',1,7);
INSERT INTO `Guns` VALUES (84,'Galil AR','Kami','Galil AR - Kami',1,7);
INSERT INTO `Guns` VALUES (85,'P90','Desert Warfare','P90 - Desert Warfare',1,7);
INSERT INTO `Guns` VALUES (86,'CZ75-Auto','Poison Dart','CZ75-Auto - Poison Dart',1,7);
INSERT INTO `Guns` VALUES (87,'AUG','Torque','AUG - Torque',2,7);
INSERT INTO `Guns` VALUES (88,'PP-Bizon','Antique','PP-Bizon - Antique',2,7);
INSERT INTO `Guns` VALUES (89,'MAC-10','Curse','MAC-10 - Curse',2,7);
INSERT INTO `Guns` VALUES (90,'XM1014','Heaven Guard','XM1014 - Heaven Guard',2,7);
INSERT INTO `Guns` VALUES (91,'M4A1-S','Atomic Alloy','M4A1-S - Atomic Alloy',3,7);
INSERT INTO `Guns` VALUES (92,'SCAR-20','Cyrex','SCAR-20 - Cyrex',3,7);
INSERT INTO `Guns` VALUES (93,'USP-S','Orion','USP-S - Orion',3,7);
INSERT INTO `Guns` VALUES (94,'AK-47','Vulcan','AK-47 - Vulcan',4,7);
INSERT INTO `Guns` VALUES (95,'M4A4','Howl','M4A4 - Howl',4,7);
INSERT INTO `Guns` VALUES (96,'Huntsman Knife','','Huntsman Knife',5,7);
INSERT INTO `Guns` VALUES (97,'Tec-9','Isaac','Tec-9 - Isaac',1,8);
INSERT INTO `Guns` VALUES (98,'SSG 08','Slashed','SSG 08 - Slashed',1,8);
INSERT INTO `Guns` VALUES (99,'Galil AR','Kami','Galil AR - Kami',1,8);
INSERT INTO `Guns` VALUES (100,'CZ75-Auto','Twist','CZ75-Auto - Twist',1,8);
INSERT INTO `Guns` VALUES (101,'P90','Module','P90 - Module',1,8);
INSERT INTO `Guns` VALUES (102,'P2000','Pulse','P2000 - Pulse',1,8);
INSERT INTO `Guns` VALUES (103,'AUG','Torque','AUG - Torque',2,8);
INSERT INTO `Guns` VALUES (104,'PP-Bizon','Antique','PP-Bizon - Antique',2,8);
INSERT INTO `Guns` VALUES (105,'MAC-10','Tatter','MAC-10 - Tatter',2,8);
INSERT INTO `Guns` VALUES (106,'XM1014','Heaven Guard','XM1014 - Heaven Guard',2,8);
INSERT INTO `Guns` VALUES (107,'M4A1-S','Atomic Alloy','M4A1-S - Atomic Alloy',3,8);
INSERT INTO `Guns` VALUES (108,'SCAR-20','Cyrex','SCAR-20 - Cyrex',3,8);
INSERT INTO `Guns` VALUES (109,'USP-S','Caiman','USP-S - Caiman',3,8);
INSERT INTO `Guns` VALUES (110,'AK-47','Vulcan','AK-47 - Vulcan',4,8);
INSERT INTO `Guns` VALUES (111,'M4A4','Desert-Strike','M4A4 - Desert-Strike',4,8);
INSERT INTO `Guns` VALUES (112,'Huntsman Knife','','Huntsman Knife',5,8);
INSERT INTO `Guns` VALUES (113,'MP7','Urban Hazard','MP7 - Urban Hazard',1,9);
INSERT INTO `Guns` VALUES (114,'Negev','Desert-Strike','Negev - Desert-Strike',1,9);
INSERT INTO `Guns` VALUES (115,'P2000','Ivory','P2000 - Ivory',1,9);
INSERT INTO `Guns` VALUES (116,'SSG 08','Abyss','SSG 08 - Abyss',1,9);
INSERT INTO `Guns` VALUES (117,'UMP-45','Labyrinth','UMP-45 - Labyrinth',1,9);
INSERT INTO `Guns` VALUES (118,'PP-Bizon','Osiris','PP-Bizon - Osiris',2,9);
INSERT INTO `Guns` VALUES (119,'CZ75-Auto','Tigris','CZ75-Auto - Tigris',2,9);
INSERT INTO `Guns` VALUES (120,'Nova','Koi','Nova - Koi',2,9);
INSERT INTO `Guns` VALUES (121,'P250','Supernova','P250 - Supernova',2,9);
INSERT INTO `Guns` VALUES (122,'Desert Eagle','Conspiracy','Desert Eagle - Conspiracy',3,9);
INSERT INTO `Guns` VALUES (123,'Five-SeveN','Fowl Play','Five-SeveN - Fowl Play',3,9);
INSERT INTO `Guns` VALUES (124,'Glock-18','Water Elemental','Glock-18 - Water Elemental',3,9);
INSERT INTO `Guns` VALUES (125,'P90','Asiimov','P90 - Asiimov',4,9);
INSERT INTO `Guns` VALUES (126,'M4A1-S','Cyrex','M4A1-S - Cyrex',4,9);
INSERT INTO `Guns` VALUES (127,'Butterfly Knife','','Butterfly Knife',5,9);
INSERT INTO `Guns` VALUES (128,'M4A4','Faded Zebra','M4A4 - Faded Zebra',1,10);
INSERT INTO `Guns` VALUES (129,'FAMAS','Doomkitty','FAMAS - Doomkitty',1,10);
INSERT INTO `Guns` VALUES (130,'MAG-7','Memento','MAG-7 - Memento',1,10);
INSERT INTO `Guns` VALUES (131,'Sawed-Off','Orange DDPAT','Sawed-Off - Orange DDPAT',2,10);
INSERT INTO `Guns` VALUES (132,'P250','Splash','P250 - Splash',2,10);
INSERT INTO `Guns` VALUES (133,'Galil AR','Orange DDPAT','Galil AR - Orange DDPAT',2,10);
INSERT INTO `Guns` VALUES (134,'AK-47','Red Laminate','AK-47 - Red Laminate',3,10);
INSERT INTO `Guns` VALUES (135,'AWP','Boom','AWP - BOOM',3,10);
INSERT INTO `Guns` VALUES (136,'P90','Death by Kitty','P90 - Death by Kitty',4,10);
INSERT INTO `Guns` VALUES (137,'Rare Special Item','','Rare Special Item',5,10);
INSERT INTO `Guns` VALUES (138,'Galil AR','Blue Titanium','Galil AR - Blue Titanium',1,11);
INSERT INTO `Guns` VALUES (139,'Five-SeveN','Nightshade','Five-SeveN - Nightshade',1,11);
INSERT INTO `Guns` VALUES (140,'PP-Bizon','Water Sigil','PP-Bizon - Water Sigil',1,11);
INSERT INTO `Guns` VALUES (141,'Nova','Ghost Camo','Nova - Ghost Camo',1,11);
INSERT INTO `Guns` VALUES (142,'G3SG1','Azure Zebra','G3SG1 - Azure Zebra',1,11);
INSERT INTO `Guns` VALUES (143,'P250','Steel Disruption','P250 - Steel Disruption',1,11);
INSERT INTO `Guns` VALUES (144,'AK-47','Blue Laminate','AK-47 - Blue Laminate',2,11);
INSERT INTO `Guns` VALUES (145,'P90','Blind Spot','P90 - Blind Spot',2,11);
INSERT INTO `Guns` VALUES (146,'FAMAS','Afterimage','FAMAS - Afterimage',3,11);
INSERT INTO `Guns` VALUES (147,'AWP','Electric Hive','AWP - Electric Hive',3,11);
INSERT INTO `Guns` VALUES (148,'Desert Eagle','Cobalt Disruption','Desert Eagle - Cobalt Disruption',3,11);
INSERT INTO `Guns` VALUES (149,'M4A4','X-Ray','M4A4 - X-Ray',4,11);
INSERT INTO `Guns` VALUES (150,'Rare Special Item','','Rare Special Item',5,11);
INSERT INTO `Guns` VALUES (151,'SSG 08','Dark Water','SSG 08 - Dark Water',1,12);
INSERT INTO `Guns` VALUES (152,'MAC-10','Ultraviolet','MAC-10 - Ultraviolet',1,12);
INSERT INTO `Guns` VALUES (153,'USP-S','Blood Tiger','USP-S - Blood Tiger',1,12);
INSERT INTO `Guns` VALUES (154,'CZ75-Auto','Hexane','CZ75-Auto - Hexane',1,12);
INSERT INTO `Guns` VALUES (155,'Negev','Bratatat','Negev - Bratatat',1,12);
INSERT INTO `Guns` VALUES (156,'XM1014','Red Python','XM1014 - Red Python',1,12);
INSERT INTO `Guns` VALUES (157,'PP-Bizon','Blue Streak','PP-Bizon - Blue Streak',2,12);
INSERT INTO `Guns` VALUES (158,'P90','Virus','P90 - Virus',2,12);
INSERT INTO `Guns` VALUES (159,'MP7','Ocean Foam','MP7 - Ocean Foam',2,12);
INSERT INTO `Guns` VALUES (160,'Glock-18','Steel Disruption','Glock-18 - Steel Disruption',2,12);
INSERT INTO `Guns` VALUES (161,'Desert Eagle','Crimson Web','Desert Eagle - Crimson Web',2,12);
INSERT INTO `Guns` VALUES (162,'AUG','Bengal Tiger','AUG - Bengal Tiger',3,12);
INSERT INTO `Guns` VALUES (163,'Nova','Bloomstick','Nova - Bloomstick',3,12);
INSERT INTO `Guns` VALUES (164,'AWP','Corticera','AWP - Corticera',3,12);
INSERT INTO `Guns` VALUES (165,'P2000','Corticera','P2000 - Corticera',3,12);
INSERT INTO `Guns` VALUES (166,'M4A4','Bullet Rain','M4A4 - Bullet Rain',4,12);
INSERT INTO `Guns` VALUES (167,'AK-47','Jaguar','AK-47 - Jaguar',4,12);
INSERT INTO `Guns` VALUES (168,'Rare Special Item','','Rare Special Item',5,12);
INSERT INTO `Guns` VALUES (169,'Lucky 13','','Lucky 13',1,13);
INSERT INTO `Guns` VALUES (170,'Aces High','','Aces High',1,13);
INSERT INTO `Guns` VALUES (171,'I Conquered','','I Conquered',1,13);
INSERT INTO `Guns` VALUES (172,'Seek & Destroy','','Seek & Destroy',1,13);
INSERT INTO `Guns` VALUES (173,'Black Dog','','Black Dog',1,13);
INSERT INTO `Guns` VALUES (174,'Fearsome','','Fearsome',1,13);
INSERT INTO `Guns` VALUES (175,'Cerberus','','Cerberus',1,13);
INSERT INTO `Guns` VALUES (176,'Easy Peasy','','Easy Peasy',1,13);
INSERT INTO `Guns` VALUES (177,'Luck Skill','','Luck Skill',1,13);
INSERT INTO `Guns` VALUES (178,'Vigilance','','Vigilance',1,13);
INSERT INTO `Guns` VALUES (179,'Aces High (Holo)','','Aces High (Holo)',2,13);
INSERT INTO `Guns` VALUES (180,'Fearsome (Holo)','','Fearsome (Holo)',2,13);
INSERT INTO `Guns` VALUES (181,'Vigilance (Holo)','','Vigilance (Holo)',2,13);
INSERT INTO `Guns` VALUES (182,'Lucky 13 (Foil)','','Lucky 13 (Foil)',3,13);
INSERT INTO `Guns` VALUES (183,'Luck Skill (Foil)','','Luck Skill (Foil)',3,13);
INSERT INTO `Guns` VALUES (184,'Banana','','Banana',1,14);
INSERT INTO `Guns` VALUES (185,'Bomb Code','','Bomb Code',1,14);
INSERT INTO `Guns` VALUES (186,'Chicken Lover','','Chicken Lover',1,14);
INSERT INTO `Guns` VALUES (187,'Good Game','','Good Game',1,14);
INSERT INTO `Guns` VALUES (188,'Good Luck','','Good Luck',1,14);
INSERT INTO `Guns` VALUES (189,'Have Fun','','Have Fun',1,14);
INSERT INTO `Guns` VALUES (190,'Lets Roll-oll','','Lets Roll-oll',1,14);
INSERT INTO `Guns` VALUES (191,'Metal','','Metal',1,14);
INSERT INTO `Guns` VALUES (192,'Nice Shot','','Nice Shot',1,14);
INSERT INTO `Guns` VALUES (193,'Welcome to the Clutch','','Welcome to the Clutch',1,14);
INSERT INTO `Guns` VALUES (194,'Bish (Holo)','','Bish (Holo)',2,14);
INSERT INTO `Guns` VALUES (195,'Bash (Holo)','','Bash (Holo)',2,14);
INSERT INTO `Guns` VALUES (196,'Bosh (Holo)','','Bosh (Holo)',2,14);
INSERT INTO `Guns` VALUES (197,'Crown (Foil)','','Crown (Foil)',3,14);
INSERT INTO `Guns` VALUES (198,'Stupid Banana (Foil)','','Stupid Banana (Foil)',3,14);
INSERT INTO `Guns` VALUES (199,'Backstab','','Backstab',1,15);
INSERT INTO `Guns` VALUES (200,'Pocket BBQ','','Pocket BBQ',1,15);
INSERT INTO `Guns` VALUES (201,'Bomb Doge','','Bomb Doge',1,15);
INSERT INTO `Guns` VALUES (202,'Burn Them All','','Burn Them All',1,15);
INSERT INTO `Guns` VALUES (203,'Llama Cannon','','Llama Cannon',1,15);
INSERT INTO `Guns` VALUES (204,'My Other Awp','','My Other Awp',1,15);
INSERT INTO `Guns` VALUES (205,'Shave Master','','Shave Master',1,15);
INSERT INTO `Guns` VALUES (206,'Rising Skull','','Rising Skull',1,15);
INSERT INTO `Guns` VALUES (207,'Sneaky Beaky Like','','Sneaky Beaky Like',1,15);
INSERT INTO `Guns` VALUES (208,'To B or not to B','','To B or not to B',1,15);
INSERT INTO `Guns` VALUES (209,'Death Comes','','Death Comes',1,15);
INSERT INTO `Guns` VALUES (210,'Teamwork (Holo)','','Teamwork (Holo)',2,15);
INSERT INTO `Guns` VALUES (211,'Rekt (Holo)','','Rekt (Holo)',2,15);
INSERT INTO `Guns` VALUES (212,'Headhunter (Foil)','','Headhunter (Foil)',3,15);
INSERT INTO `Guns` VALUES (213,'Flammable (Foil)','','Flammable (Foil)',3,15);
INSERT INTO `Guns` VALUES (214,'New Sheriff (Foil)','','New Sheriff (Foil)',3,15);
INSERT INTO `Guns` VALUES (215,'Swag (Foil)','','Swag (Foil)',3,15);
INSERT INTO `Guns` VALUES (216,'3DMAX','Katowice 2014','3DMAX - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (217,'iBUYPOWER','Katowice 2014','iBUYPOWER - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (218,'mousesports','Katowice 2014','mousesports - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (219,'Clan-Mystik','Katowice 2014','Clan-Mystik - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (220,'Natus Vincere','Katowice 2014','Natus Vincere - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (221,'Reason Gaming','Katowice 2014','Reason Gaming - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (222,'Virtus.Pro','Katowice 2014','Virtus.Pro - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (223,'Vox Eminor','Katowice 2014','Vox Eminor - Katowice 2014',1,16);
INSERT INTO `Guns` VALUES (224,'3DMAX (Holo)','Katowice 2014','3DMAX (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (225,'iBUYPOWER (Holo)','Katowice 2014','iBUYPOWER (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (226,'mousesports (Holo)','Katowice 2014','mousesports (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (227,'Clan-Mystik (Holo)','Katowice 2014','Clan-Mystik (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (228,'Natus Vincere (Holo)','Katowice 2014','Natus Vincere (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (229,'Reason Gaming (Holo)','Katowice 2014','Reason Gaming (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (230,'Virtus.Pro (Holo)','Katowice 2014','Virtus.Pro (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (231,'Vox Eminor (Holo)','Katowice 2014','Vox Eminor (Holo) - Katowice 2014',2,16);
INSERT INTO `Guns` VALUES (232,'ESL Wolf (Foil)','Katowice 2014','ESL Wolf (Foil) - Katowice 2014',3,16);
INSERT INTO `Guns` VALUES (233,'compLexity Gaming','Katowice 2014','compLexity Gaming - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (234,'Team Dignitas','Katowice 2014','Team Dignitas - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (235,'Fnatic','Katowice 2014','Fnatic - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (236,'HellRaisers','Katowice 2014','HellRaisers - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (237,'Team LDLC.com','Katowice 2014','Team LDLC.com - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (238,'LGB eSports','Katowice 2014','LGB eSports - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (239,'Ninjas in Pyjamas','Katowice 2014','Ninjas in Pyjamas - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (240,'Titan','Katowice 2014','Titan - Katowice 2014',1,17);
INSERT INTO `Guns` VALUES (241,'compLexity Gaming (Holo)','Katowice 2014','compLexity Gaming (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (242,'Team Dignitas (Holo)','Katowice 2014','Team Dignitas (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (243,'Fnatic (Holo)','Katowice 2014','Fnatic (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (244,'HellRaisers (Holo)','Katowice 2014','HellRaisers (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (245,'Team LDLC.com (Holo)','Katowice 2014','Team LDLC.com (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (246,'LGB eSports (Holo)','Katowice 2014','LGB eSports (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (247,'Ninjas in Pyjamas (Holo)','Katowice 2014','Ninjas in Pyjamas (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (248,'Titan (Holo)','Katowice 2014','Titan (Holo) - Katowice 2014',2,17);
INSERT INTO `Guns` VALUES (249,'ESL Skull (Foil)','Katowice 2014','ESL Skull (Foil) - Katowice 2014',3,17);
INSERT INTO `Guns` VALUES (250,'Copenhagen Wolves','Cologne 2014','Copenhagen Wolves - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (251,'dAT team','Cologne 2014','dAT team - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (252,'Epsilon eSports','Cologne 2014','Epsilon eSports - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (253,'iBUYPOWER','Cologne 2014','iBUYPOWER - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (254,'London Conspiracy','Cologne 2014','London Conspiracy - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (255,'Natus Vincere','Cologne 2014','Natus Vincere - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (256,'Titan','Cologne 2014','Titan - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (257,'Vox Eminor','Cologne 2014','Vox Eminor - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (258,'MTS GameGod Wolf','Cologne 2014','MTS GameGod Wolf - Cologne 2014',1,18);
INSERT INTO `Guns` VALUES (259,'Copenhagen Wolves (Holo)','Cologne 2014','Copenhagen Wolves (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (260,'dAT team (Holo)','Cologne 2014','dAT team (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (261,'Epsilon eSports (Holo)','Cologne 2014','Epsilon eSports (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (262,'iBUYPOWER (Holo)','Cologne 2014','iBUYPOWER (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (263,'London Conspiracy (Holo)','Cologne 2014','London Conspiracy (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (264,'Natus Vincere (Holo)','Cologne 2014','Natus Vincere (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (265,'Titan (Holo)','Cologne 2014','Titan (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (266,'Vox Eminor (Holo)','Cologne 2014','Vox Eminor (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (267,'MTS GameGod Wolf (Holo)','Cologne 2014','MTS GameGod Wolf (Holo) - Cologne 2014',2,18);
INSERT INTO `Guns` VALUES (268,'ESL One Cologne 2014 (Red)','','ESL One Cologne 2014 (Red)',3,18);
INSERT INTO `Guns` VALUES (269,'Cloud9','Cologne 2014','Cloud9 - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES (270,'Fnatic','Cologne 2014','Fnatic - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES (271,'HellRaisers','Cologne 2014','HellRaisers - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES (272,'Ninjas in Pyjamas','Cologne 2014','Ninjas in Pyjamas - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES (273,'Team Dignitas','Cologne 2014','Team Dignitas - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES (274,'Team LDLC.com','Cologne 2014','Team LDLC.com - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES (275,'Virtus.Pro','Cologne 2014','Virtus.Pro - Cologne 2014',1,19);
INSERT INTO `Guns` VALUES (276,'Cloud9 (Holo)','Cologne 2014','Cloud9 (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES (277,'Fnatic (Holo)','Cologne 2014','Fnatic (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES (278,'HellRaisers (Holo)','Cologne 2014','HellRaisers (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES (279,'Ninjas in Pyjamas (Holo)','Cologne 2014','Ninjas in Pyjamas (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES (280,'Team Dignitas (Holo)','Cologne 2014','Team Dignitas (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES (281,'Team LDLC.com (Holo)','Cologne 2014','Team LDLC.com (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES (282,'Virtus.Pro (Holo)','Cologne 2014','Virtus.Pro (Holo) - Cologne 2014',2,19);
INSERT INTO `Guns` VALUES (283,'ESL One Cologne 2014 (Blue)','','ESL One Cologne 2014 (Blue)',3,19);
INSERT INTO `Guns` VALUES (284,'G3SG1','Murky','G3SG1 - Murky',1,20);
INSERT INTO `Guns` VALUES (285,'MAG-7','Firestarter','MAG-7 - Firestarter',1,20);
INSERT INTO `Guns` VALUES (286,'MP9','Dart','MP9 - Dart',1,20);
INSERT INTO `Guns` VALUES (287,'Five-SeveN','Urban Hazard','Five-SeveN - Urban Hazard',1,20);
INSERT INTO `Guns` VALUES (288,'UMP-45','Delusion','UMP-45 - Delusion',1,20);
INSERT INTO `Guns` VALUES (289,'Glock-18','Grinder','Glock-18 - Grinder',2,20);
INSERT INTO `Guns` VALUES (290,'M4A1-S','Basilisk','M4A1-S - Basilisk',2,20);
INSERT INTO `Guns` VALUES (291,'M4A4','Griffin','M4A4 - Griffin',2,20);
INSERT INTO `Guns` VALUES (292,'Sawed-Off','Highwayman','Sawed-Off - Highwayman',2,20);
INSERT INTO `Guns` VALUES (293,'P250','Cartel','P250 - Cartel',3,20);
INSERT INTO `Guns` VALUES (294,'SCAR-20','Cardiac','SCAR-20 - Cardiac',3,20);
INSERT INTO `Guns` VALUES (295,'XM1014','Tranquility','XM1014 - Tranquility',3,20);
INSERT INTO `Guns` VALUES (296,'AK-47','Wasteland Rebel','AK-47 - Wasteland Rebel',4,20);
INSERT INTO `Guns` VALUES (297,'P2000','Fire Elemental','P2000 - Fire Elemental',4,20);
INSERT INTO `Guns` VALUES (298,'Rare Special Item','','Rare Special Item',5,20);
INSERT INTO `Guns` VALUES (299,'Glock-18','Catacombs','Glock-18 - Catacombs',1,21);
INSERT INTO `Guns` VALUES (300,'M249','System Lock','M249 - System Lock',1,21);
INSERT INTO `Guns` VALUES (301,'MP9','Deadly Poison','MP9 - Deadly Poison',1,21);
INSERT INTO `Guns` VALUES (302,'SCAR-20','Grotto','SCAR-20 - Grotto',1,21);
INSERT INTO `Guns` VALUES (303,'XM1014','Quicksilver','XM1014 - Quicksilver',1,21);
INSERT INTO `Guns` VALUES (304,'Dual Berettas','Urban Shock','Dual Berettas - Urban Shock',2,21);
INSERT INTO `Guns` VALUES (305,'Desert Eagle','Naga','Desert Eagle - Naga',2,21);
INSERT INTO `Guns` VALUES (306,'MAC-10','Malachite','MAC-10 - Malachite',2,21);
INSERT INTO `Guns` VALUES (307,'Sawed-Off','Serenity','Sawed-Off - Serenity',2,21);
INSERT INTO `Guns` VALUES (308,'AK-47','Cartel','AK-47 - Cartel',3,21);
INSERT INTO `Guns` VALUES (309,'M4A4','Dragon King','M4A4 - Dragon King',3,21);
INSERT INTO `Guns` VALUES (310,'P250','Muertos','P250 - Muertos',3,21);
INSERT INTO `Guns` VALUES (311,'AWP','Man-o''-war','AWP - Man-o''-war',4,21);
INSERT INTO `Guns` VALUES (312,'Galil AR','Chatterbox','Galil AR - Chatterbox',4,21);
INSERT INTO `Guns` VALUES (313,'Rare Special Item','','Rare Special Item',5,21);
INSERT INTO `Guns` VALUES (314,'Rare Special Item','','Rare Special Item',5,3);
INSERT INTO `Guns` VALUES (315,'Rare Special Item','','Rare Special Item',5,4);
INSERT INTO `Guns` VALUES (316,'AK-47','Elite Build','AK-47 - Elite Build',1,22);
INSERT INTO `Guns` VALUES (317,'MP7','Armor Core','MP7 - Armor Core',1,22);
INSERT INTO `Guns` VALUES (318,'Desert Eagle','Bronze Deco','Desert Eagle - Bronze Deco',1,22);
INSERT INTO `Guns` VALUES (319,'P250','Valence','P250 - Valence',1,22);
INSERT INTO `Guns` VALUES (320,'Negev','Man-o''-war','Negev - Man-o''-war',1,22);
INSERT INTO `Guns` VALUES (321,'Sawed-Off','Origami','Sawed-Off - Origami',1,22);
INSERT INTO `Guns` VALUES (322,'AWP','Worm God','AWP - Worm God',2,22);
INSERT INTO `Guns` VALUES (323,'MAG-7','Heat','MAG-7 - Heat',2,22);
INSERT INTO `Guns` VALUES (324,'CZ75-Auto','Pole Position','CZ75-Auto - Pole Position',2,22);
INSERT INTO `Guns` VALUES (325,'UMP-45','Grand Prix','UMP-45 - Grand Prix',2,22);
INSERT INTO `Guns` VALUES (326,'Five-SeveN','Monkey Business','Five-SeveN - Monkey Business',3,22);
INSERT INTO `Guns` VALUES (327,'Galil AR','Eco','Galil AR - Eco',3,22);
INSERT INTO `Guns` VALUES (328,'FAMAS','Djinn','FAMAS - Djinn',3,22);
INSERT INTO `Guns` VALUES (329,'M4A1-S','Hyper Beast','M4A1-S - Hyper Beast',4,22);
INSERT INTO `Guns` VALUES (330,'MAC-10','Neon Rider','MAC-10 - Neon Rider',4,22);
INSERT INTO `Guns` VALUES (331,'Rare Special Item','','Rare Special Item',5,22);
INSERT INTO `Guns` VALUES (332,'Galil AR','Rocket Pop','Galil AR - Rocket Pop',1,23);
INSERT INTO `Guns` VALUES (333,'Glock-18','Bunsen Burner','Glock-18 - Bunsen Burner',1,23);
INSERT INTO `Guns` VALUES (334,'Nova','Ranger','Nova - Ranger',1,23);
INSERT INTO `Guns` VALUES (335,'P90','Elite Build','P90 - Elite Build',1,23);
INSERT INTO `Guns` VALUES (336,'UMP-45','Riot','UMP-45 - Riot',1,23);
INSERT INTO `Guns` VALUES (337,'USP-S','Torque','USP-S - Torque',1,23);
INSERT INTO `Guns` VALUES (338,'FAMAS','Neural Net','FAMAS - Neural Net',2,23);
INSERT INTO `Guns` VALUES (339,'M4A4','Evil Daimyo','M4A4 - Evil Daimyo',2,23);
INSERT INTO `Guns` VALUES (340,'MP9','Ruby Poison Dart','MP9 - Ruby Poison Dart',2,23);
INSERT INTO `Guns` VALUES (341,'Negev','Loudmouth','Negev - Loudmouth',2,23);
INSERT INTO `Guns` VALUES (342,'P2000','Handgun','P2000 - Handgun',2,23);
INSERT INTO `Guns` VALUES (343,'CZ75-Auto','Yellow Jacket','CZ75-Auto - Yellow Jacket',3,23);
INSERT INTO `Guns` VALUES (344,'MP7','Nemesis','MP7 - Nemesis',3,23);
INSERT INTO `Guns` VALUES (345,'SG 553','Cyrex','SG 553 - Cyrex',3,23);
INSERT INTO `Guns` VALUES (346,'AK-47','Aquamarine Revenge','AK-47 - Aquamarine Revenge',4,23);
INSERT INTO `Guns` VALUES (347,'AWP','Hyper Beast','AWP - Hyper Beast',4,23);
INSERT INTO `Guns` VALUES (348,'Falchion Knife','','Falchion Knife',5,23);
INSERT INTO `Guns` VALUES (349,'Fnatic (Holo)','DreamHack 2014','Fnatic (Holo) - DreamHack 2014',2,24);
INSERT INTO `Guns` VALUES (350,'Cloud9 (Holo)','DreamHack 2014','Cloud9 (Holo) - DreamHack 2014',2,24);
INSERT INTO `Guns` VALUES (351,'Virtus.Pro (Holo)','DreamHack 2014','Virtus.Pro (Holo) - DreamHack 2014',2,24);
INSERT INTO `Guns` VALUES (352,'Ninjas in Pyjamas (Holo)','DreamHack 2014','Ninjas in Pyjamas (Holo) - DreamHack 2014',2,24);
INSERT INTO `Guns` VALUES (353,'Natus Vincere (Holo)','DreamHack 2014','Natus Vincere (Holo) - DreamHack 2014',2,24);
INSERT INTO `Guns` VALUES (354,'Team Dignitas (Holo)','DreamHack 2014','Team Dignitas (Holo) - DreamHack 2014',2,24);
INSERT INTO `Guns` VALUES (355,'Fnatic (Foil)','DreamHack 2014','Fnatic (Foil) - DreamHack 2014',3,24);
INSERT INTO `Guns` VALUES (356,'Cloud9 (Foil)','DreamHack 2014','Cloud9 (Foil) - DreamHack 2014',3,24);
INSERT INTO `Guns` VALUES (357,'Virtus.Pro (Foil)','DreamHack 2014','Virtus.Pro (Foil) - DreamHack 2014',3,24);
INSERT INTO `Guns` VALUES (358,'Ninjas in Pyjamas (Foil)','DreamHack 2014','Ninjas in Pyjamas (Foil) - DreamHack 2014',3,24);
INSERT INTO `Guns` VALUES (359,'Natus Vincere (Foil)','DreamHack 2014','Natus Vincere (Foil) - DreamHack 2014',3,24);
INSERT INTO `Guns` VALUES (360,'Team Dignitas (Foil)','DreamHack 2014','Team Dignitas (Foil) - DreamHack 2014',3,24);
INSERT INTO `Guns` VALUES (361,'DreamHack Winter 2014 (Foil)','','DreamHack Winter 2014 (Foil)',3,24);
INSERT INTO `Guns` VALUES (362,'3DMAX (Holo)','Katowice 2015','3DMAX (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (363,'Cloud9 G2A (Holo)','Katowice 2015','Cloud9 G2A (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (364,'Counter Logic Gaming (Holo)','Katowice 2015','Counter Logic Gaming (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (365,'Flipsid3 Tactics (Holo)','Katowice 2015','Flipsid3 Tactics (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (366,'Keyd Stars (Holo)','Katowice 2015','Keyd Stars (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (367,'LGB eSports (Holo)','Katowice 2015','LGB eSports (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (368,'Titan (Holo)','Katowice 2015','Titan (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (369,'Vox Eminor (Holo)','Katowice 2015','Vox Eminor (Holo) - Katowice 2015',2,25);
INSERT INTO `Guns` VALUES (370,'3DMAX (Foil)','Katowice 2015','3DMAX (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (371,'Cloud9 G2A (Foil)','Katowice 2015','Cloud9 G2A (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (372,'Counter Logic Gaming (Foil)','Katowice 2015','Counter Logic Gaming (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (373,'Flipsid3 Tactics (Foil)','Katowice 2015','Flipsid3 Tactics (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (374,'Keyd Stars (Foil)','Katowice 2015','Keyd Stars (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (375,'LGB eSports (Foil)','Katowice 2015','LGB eSports (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (376,'Titan (Foil)','Katowice 2015','Titan (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (377,'Vox Eminor (Foil)','Katowice 2015','Vox Eminor (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (378,'ESL One (Foil)','Katowice 2015','ESL One (Foil) - Katowice 2015',3,25);
INSERT INTO `Guns` VALUES (379,'Fnatic (Holo)','Katowice 2015','Fnatic (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (380,'HellRaisers (Holo)','Katowice 2015','HellRaisers (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (381,'Natus Vincere (Holo)','Katowice 2015','Natus Vincere (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (382,'Ninjas in Pyjamas (Holo)','Katowice 2015','Ninjas in Pyjamas (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (383,'PENTA Sports (Holo)','Katowice 2015','PENTA Sports (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (384,'Team EnVyUs (Holo)','Katowice 2015','Team EnVyUs (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (385,'TSM Kinguin (Holo)','Katowice 2015','TSM Kinguin (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (386,'Virtus.pro (Holo)','Katowice 2015','Virtus.pro (Holo) - Katowice 2015',2,26);
INSERT INTO `Guns` VALUES (387,'Fnatic (Foil)','Katowice 2015','Fnatic (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (388,'HellRaisers (Foil)','Katowice 2015','HellRaisers (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (389,'Natus Vincere (Foil)','Katowice 2015','Natus Vincere (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (390,'Ninjas in Pyjamas (Foil)','Katowice 2015','Ninjas in Pyjamas (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (391,'PENTA Sports (Foil)','Katowice 2015','PENTA Sports (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (392,'Team EnVyUs (Foil)','Katowice 2015','Team EnVyUs (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (393,'TSM Kinguin (Foil)','Katowice 2015','TSM Kinguin (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (394,'Virtus.pro (Foil)','Katowice 2015','Virtus.pro (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (395,'ESL One (Foil)','Katowice 2015','ESL One (Foil) - Katowice 2015',3,26);
INSERT INTO `Guns` VALUES (396,'Dual Berettas','Dualing Dragons','Dual Berettas - Dualing Dragons',1,27);
INSERT INTO `Guns` VALUES (397,'FAMAS','Survivor Z','FAMAS - Survivor Z',1,27);
INSERT INTO `Guns` VALUES (398,'Glock-18','Wraiths','Glock-18 - Wraiths',1,27);
INSERT INTO `Guns` VALUES (399,'MAC-10','Rangeen','MAC-10 - Rangeen',1,27);
INSERT INTO `Guns` VALUES (400,'MAG-7','Cobalt Core','MAG-7 - Cobalt Core',1,27);
INSERT INTO `Guns` VALUES (401,'SCAR-20','Green Marine','SCAR-20 - Green Marine',1,27);
INSERT INTO `Guns` VALUES (402,'XM1014','Scumbria','XM1014 - Scumbria',1,27);
INSERT INTO `Guns` VALUES (403,'Galil AR','Stone Cold','Galil AR - Stone Cold',2,27);
INSERT INTO `Guns` VALUES (404,'M249','Nebula Crusader','M249 - Nebula Crusader',2,27);
INSERT INTO `Guns` VALUES (405,'MP7','Special Delivery','MP7 - Special Delivery',2,27);
INSERT INTO `Guns` VALUES (406,'P250','Wingshot','P250 - Wingshot',2,27);
INSERT INTO `Guns` VALUES (407,'AK-47','Frontside Misty','AK-47 - Frontside Misty',3,27);
INSERT INTO `Guns` VALUES (408,'G3SG1','Flux','G3SG1 - Flux',3,27);
INSERT INTO `Guns` VALUES (409,'SSG 08','Big Iron','SSG 08 - Big Iron',3,27);
INSERT INTO `Guns` VALUES (410,'M4A1-S','Golden Coil','M4A1-S - Golden Coil',4,27);
INSERT INTO `Guns` VALUES (411,'USP-S','Kill Confirmed','USP-S - Kill Confirmed',4,27);
INSERT INTO `Guns` VALUES (412,'Shadow Daggers','','Shadow Daggers',5,27);
INSERT INTO `Guns` VALUES (413,'Renegades (Foil)','Cologne 2015','Renegades (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (414,'Team Kinguin (Foil)','Cologne 2015','Team Kinguin (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (415,'Team eBettle (Foil)','Cologne 2015','Team eBettle (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (416,'Cloud9 G2A (Foil)','Cologne 2015','Cloud9 G2A (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (417,'Team Immunity (Foil)','Cologne 2015','Team Immunity (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (418,'Flipsid3 Tactics (Foil)','Cologne 2015','Flipsid3 Tactics (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (419,'Titan (Foil)','Cologne 2015','Titan (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (420,'Counter Logic Gaming (Foil)','Cologne 2015','Counter Logic Gaming (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (421,'ESL (Foil) - Cologne 2015','Cologne 2015','ESL (Foil) - Cologne 2015',3,28);
INSERT INTO `Guns` VALUES (422,'Fnatic (Foil)','Cologne 2015','Fnatic (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (423,'Virtus.Pro (Foil)','Cologne 2015','Virtus.Pro (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (424,'mousesports (Foil)','Cologne 2015','mousesports (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (425,'Natus Vincere (Foil)','Cologne 2015','Natus Vincere (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (426,'Ninjas in Pyjamas (Foil)','Cologne 2015','Ninjas in Pyjamas (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (427,'Team EnVyUs (Foil)','Cologne 2015','Team EnVyUs (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (428,'Luminosity Gaming (Foil)','Cologne 2015','Luminosity Gaming (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (429,'Team SoloMid (Foil)','Cologne 2015','Team SoloMid (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (430,'ESL (Foil)','Cologne 2015','ESL (Foil) - Cologne 2015',3,29);
INSERT INTO `Guns` VALUES (431,'Chabo','','Chabo',1,30);
INSERT INTO `Guns` VALUES (432,'Bombsquad','','Bombsquad',1,30);
INSERT INTO `Guns` VALUES (433,'Skulltorgeist','','Skulltorgeist',1,30);
INSERT INTO `Guns` VALUES (434,'The Guru','','The Guru',1,30);
INSERT INTO `Guns` VALUES (435,'Silent Ninja','','Silent Ninja',1,30);
INSERT INTO `Guns` VALUES (436,'The Samurai','','The Samurai',1,30);
INSERT INTO `Guns` VALUES (437,'Skull Troop','','Skull Troop',1,30);
INSERT INTO `Guns` VALUES (438,'Salute!','','Salute!',1,30);
INSERT INTO `Guns` VALUES (439,'The Spartan','','The Spartan',1,30);
INSERT INTO `Guns` VALUES (440,'Unicorn','','Unicorn',1,30);
INSERT INTO `Guns` VALUES (441,'Skull Lil Boney','','Skull Lil Boney',1,30);
INSERT INTO `Guns` VALUES (442,'The Zombie','','The Zombie',1,30);
INSERT INTO `Guns` VALUES (443,'Unicorn (Holo)','','Unicorn (Holo)',2,30);
INSERT INTO `Guns` VALUES (444,'Bombsquad (Foil)','','Bombsquad (Foil)',3,30);
INSERT INTO `Guns` VALUES (445,'Silent Ninja (Foil)','','Silent Ninja (Foil)',3,30);
CREATE TABLE "EventStickers" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`evStickType`	TEXT,
	`evStickSkin`	TEXT,
	`evStickTexture`	TEXT NOT NULL,
	`rarity`	TEXT NOT NULL,
	`spawnRarity`	TEXT NOT NULL,
	`startDate`	TEXT NOT NULL,
	`endDate`	TEXT NOT NULL
);
INSERT INTO `EventStickers` VALUES (1,'Christmas','2014','Christmas - 2014','2','2','11 12 2014','30 12 2014');
INSERT INTO `EventStickers` VALUES (2,'New Years','2015','New Years - 2015','2','2','24 12 2014 ','07 01 2015');
CREATE TABLE "Cases" (
	`_id`	INTEGER NOT NULL,
	`caseName`	TEXT NOT NULL,
	`caseTexture`	TEXT NOT NULL,
	`type`	TEXT NOT NULL
);
INSERT INTO `Cases` VALUES (1,'Weapons Case 1','CSGO 1','case');
INSERT INTO `Cases` VALUES (2,'Weapons Case 2','CSGO 2','case');
INSERT INTO `Cases` VALUES (3,'Weapons Case 3','CSGO 3','case');
INSERT INTO `Cases` VALUES (4,'Operation Bravo Case','Operation Bravo','case');
INSERT INTO `Cases` VALUES (5,'Winter Offensive Case','Winter Offensive','case');
INSERT INTO `Cases` VALUES (6,'Operation Phoenix Case','Operation Phoenix','case');
INSERT INTO `Cases` VALUES (7,'Huntsman Case (Old)','Huntsman','case');
INSERT INTO `Cases` VALUES (8,'Huntsman Case (New)','Huntsman','case');
INSERT INTO `Cases` VALUES (9,'Operation Breakout Case','Operation Breakout','case');
INSERT INTO `Cases` VALUES (20,'Operation Vanguard Case','Operation Vanguard','case');
INSERT INTO `Cases` VALUES (21,'Chroma Case','Chroma','case');
INSERT INTO `Cases` VALUES (22,'Chroma 2 Case','Chroma 2','case');
INSERT INTO `Cases` VALUES (23,'Falchion Case','Falchion','case');
INSERT INTO `Cases` VALUES (27,'Shadow Case','Shadow','case');
INSERT INTO `Cases` VALUES (10,'eSports 2013 Case','eSports 2013','esport');
INSERT INTO `Cases` VALUES (11,'eSports 2013 Winter Case','eSports 2013 Winter','esport');
INSERT INTO `Cases` VALUES (12,'eSports 2014 Summer Case','eSports 2014 Summer','esport');
INSERT INTO `Cases` VALUES (13,'Sticker Capsule 1','Sticker 1','sticker');
INSERT INTO `Cases` VALUES (14,'Sticker Capsule 2','Sticker 2','sticker');
INSERT INTO `Cases` VALUES (15,'Community Sticker Capsule 1','Community Sticker 1','sticker');
INSERT INTO `Cases` VALUES (30,'Enfu Sticker Capsule','Enfu','sticker');
INSERT INTO `Cases` VALUES (16,'EMS Katowice 2014 Challengers','EMS Katowice 2014 Challengers','sticker');
INSERT INTO `Cases` VALUES (17,'EMS Katowice 2014 Legends','EMS Katowice 2014 Legends','sticker');
INSERT INTO `Cases` VALUES (18,'ESL One Cologne 2014 Challengers','ESL One Cologne 2014 Challengers','sticker');
INSERT INTO `Cases` VALUES (19,'ESL One Cologne 2014 Legends','ESL One Cologne 2014 Legends','sticker');
INSERT INTO `Cases` VALUES (24,'DreamHack 2014 Legends','DreamHack 2014 Legends','sticker');
INSERT INTO `Cases` VALUES (25,'ESL One Katowice 2015 Challengers','ESL One Katowice 2015 Challengers','sticker');
INSERT INTO `Cases` VALUES (26,'ESL One Katowice 2015 Legends','ESL One Katowice 2015 Legends','sticker');
INSERT INTO `Cases` VALUES (28,'ESL One Cologne 2015 Challengers','ESL One Cologne 2015 Challengers','sticker');
INSERT INTO `Cases` VALUES (29,'ESL One Cologne 2015 Legends','ESL One Cologne 2015 Legends','sticker');